/*
 * Ex Libris APIs
 * For more information on how to use these APIs, including how to create an API key required for authentication, see [Alma REST APIs](https://developers.exlibrisgroup.com/alma/apis).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.unidue.ub.alma.shared.acq;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import javax.xml.bind.annotation.*;

/**
 * AccessInfo2
 */
@JsonPropertyOrder({
  AccessInfo.JSON_PROPERTY_USER_ID,
  AccessInfo.JSON_PROPERTY_USER_PASSWORD,
  AccessInfo.JSON_PROPERTY_USER_PASS_NOTE,
  AccessInfo.JSON_PROPERTY_IP_ADDRESS_REG_METHOD,
  AccessInfo.JSON_PROPERTY_IP_ADDRESS_REG_INSTRUCTIONS,
  AccessInfo.JSON_PROPERTY_IP_ADDRESS_NOTE,
  AccessInfo.JSON_PROPERTY_ACCESS_NOTE,
  AccessInfo.JSON_PROPERTY_PRIMARY_ACCESS_URI,
  AccessInfo.JSON_PROPERTY_INTERFACE_URI,
  AccessInfo.JSON_PROPERTY_IMPLEMENTED_AUTH_METHOD,
  AccessInfo.JSON_PROPERTY_LOCAL_PERSISTENT_URI
})

@XmlRootElement(name = "access_info")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "access_info")
public class AccessInfo implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_USER_ID = "user_id";
  @XmlElement(name = "user_id")
  private String userId;

  public static final String JSON_PROPERTY_USER_PASSWORD = "user_password";
  @XmlElement(name = "user_password")
  private String userPassword;

  public static final String JSON_PROPERTY_USER_PASS_NOTE = "user_pass_note";
  @XmlElement(name = "user_pass_note")
  private String userPassNote;

  public static final String JSON_PROPERTY_IP_ADDRESS_REG_METHOD = "ip_address_reg_method";
  @XmlElement(name = "ip_address_reg_method")
  private AccessInfoIpAddressRegMethod ipAddressRegMethod;

  public static final String JSON_PROPERTY_IP_ADDRESS_REG_INSTRUCTIONS = "ip_address_reg_instructions";
  @XmlElement(name = "ip_address_reg_instructions")
  private String ipAddressRegInstructions;

  public static final String JSON_PROPERTY_IP_ADDRESS_NOTE = "ip_address_note";
  @XmlElement(name = "ip_address_note")
  private String ipAddressNote;

  public static final String JSON_PROPERTY_ACCESS_NOTE = "access_note";
  @XmlElement(name = "access_note")
  private String accessNote;

  public static final String JSON_PROPERTY_PRIMARY_ACCESS_URI = "primary_access_uri";
  @XmlElement(name = "primary_access_uri")
  private String primaryAccessUri;

  public static final String JSON_PROPERTY_INTERFACE_URI = "interface_uri";
  @XmlElement(name = "interface_uri")
  private String interfaceUri;

  public static final String JSON_PROPERTY_IMPLEMENTED_AUTH_METHOD = "implemented_auth_method";
  @XmlElement(name = "implemented_auth_method")
  private AccessInfoImplementedAuthMethod implementedAuthMethod;

  public static final String JSON_PROPERTY_LOCAL_PERSISTENT_URI = "local_persistent_uri";
  @XmlElement(name = "local_persistent_uri")
  private String localPersistentUri;


  public AccessInfo userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * The user id for security purposes.
   * @return userId
  **/

  @ApiModelProperty(value = "The user id for security purposes.")
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "user_id")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  public AccessInfo userPassword(String userPassword) {
    
    this.userPassword = userPassword;
    return this;
  }

   /**
   * The user password for security purposes.
   * @return userPassword
  **/

  @ApiModelProperty(value = "The user password for security purposes.")
  @JsonProperty(JSON_PROPERTY_USER_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "user_password")

  public String getUserPassword() {
    return userPassword;
  }


  public void setUserPassword(String userPassword) {
    this.userPassword = userPassword;
  }


  public AccessInfo userPassNote(String userPassNote) {
    
    this.userPassNote = userPassNote;
    return this;
  }

   /**
   * The user password&#39;s related note.
   * @return userPassNote
  **/

  @ApiModelProperty(value = "The user password's related note.")
  @JsonProperty(JSON_PROPERTY_USER_PASS_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "user_pass_note")

  public String getUserPassNote() {
    return userPassNote;
  }


  public void setUserPassNote(String userPassNote) {
    this.userPassNote = userPassNote;
  }


  public AccessInfo ipAddressRegMethod(AccessInfoIpAddressRegMethod ipAddressRegMethod) {
    
    this.ipAddressRegMethod = ipAddressRegMethod;
    return this;
  }

   /**
   * Get ipAddressRegMethod
   * @return ipAddressRegMethod
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IP_ADDRESS_REG_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ip_address_reg_method")

  public AccessInfoIpAddressRegMethod getIpAddressRegMethod() {
    return ipAddressRegMethod;
  }


  public void setIpAddressRegMethod(AccessInfoIpAddressRegMethod ipAddressRegMethod) {
    this.ipAddressRegMethod = ipAddressRegMethod;
  }


  public AccessInfo ipAddressRegInstructions(String ipAddressRegInstructions) {
    
    this.ipAddressRegInstructions = ipAddressRegInstructions;
    return this;
  }

   /**
   * The URI at which IP addresses are registered, the email address or contact role to which updates are sent, or other relevant instructions.
   * @return ipAddressRegInstructions
  **/

  @ApiModelProperty(value = "The URI at which IP addresses are registered, the email address or contact role to which updates are sent, or other relevant instructions.")
  @JsonProperty(JSON_PROPERTY_IP_ADDRESS_REG_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ip_address_reg_instructions")

  public String getIpAddressRegInstructions() {
    return ipAddressRegInstructions;
  }


  public void setIpAddressRegInstructions(String ipAddressRegInstructions) {
    this.ipAddressRegInstructions = ipAddressRegInstructions;
  }


  public AccessInfo ipAddressNote(String ipAddressNote) {
    
    this.ipAddressNote = ipAddressNote;
    return this;
  }

   /**
   * Additional notes pertaining to IP address information.
   * @return ipAddressNote
  **/

  @ApiModelProperty(value = "Additional notes pertaining to IP address information.")
  @JsonProperty(JSON_PROPERTY_IP_ADDRESS_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "ip_address_note")

  public String getIpAddressNote() {
    return ipAddressNote;
  }


  public void setIpAddressNote(String ipAddressNote) {
    this.ipAddressNote = ipAddressNote;
  }


  public AccessInfo accessNote(String accessNote) {
    
    this.accessNote = accessNote;
    return this;
  }

   /**
   * Get accessNote
   * @return accessNote
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACCESS_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "access_note")

  public String getAccessNote() {
    return accessNote;
  }


  public void setAccessNote(String accessNote) {
    this.accessNote = accessNote;
  }


  public AccessInfo primaryAccessUri(String primaryAccessUri) {
    
    this.primaryAccessUri = primaryAccessUri;
    return this;
  }

   /**
   * The method of access, the location, and the file name of an e-product.
   * @return primaryAccessUri
  **/

  @ApiModelProperty(value = "The method of access, the location, and the file name of an e-product.")
  @JsonProperty(JSON_PROPERTY_PRIMARY_ACCESS_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "primary_access_uri")

  public String getPrimaryAccessUri() {
    return primaryAccessUri;
  }


  public void setPrimaryAccessUri(String primaryAccessUri) {
    this.primaryAccessUri = primaryAccessUri;
  }


  public AccessInfo interfaceUri(String interfaceUri) {
    
    this.interfaceUri = interfaceUri;
    return this;
  }

   /**
   * Get interfaceUri
   * @return interfaceUri
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INTERFACE_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "interface_uri")

  public String getInterfaceUri() {
    return interfaceUri;
  }


  public void setInterfaceUri(String interfaceUri) {
    this.interfaceUri = interfaceUri;
  }


  public AccessInfo implementedAuthMethod(AccessInfoImplementedAuthMethod implementedAuthMethod) {
    
    this.implementedAuthMethod = implementedAuthMethod;
    return this;
  }

   /**
   * Get implementedAuthMethod
   * @return implementedAuthMethod
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IMPLEMENTED_AUTH_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "implemented_auth_method")

  public AccessInfoImplementedAuthMethod getImplementedAuthMethod() {
    return implementedAuthMethod;
  }


  public void setImplementedAuthMethod(AccessInfoImplementedAuthMethod implementedAuthMethod) {
    this.implementedAuthMethod = implementedAuthMethod;
  }


  public AccessInfo localPersistentUri(String localPersistentUri) {
    
    this.localPersistentUri = localPersistentUri;
    return this;
  }

   /**
   * Get localPersistentUri
   * @return localPersistentUri
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCAL_PERSISTENT_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "local_persistent_uri")

  public String getLocalPersistentUri() {
    return localPersistentUri;
  }


  public void setLocalPersistentUri(String localPersistentUri) {
    this.localPersistentUri = localPersistentUri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessInfo accessInfo = (AccessInfo) o;
    return Objects.equals(this.userId, accessInfo.userId) &&
        Objects.equals(this.userPassword, accessInfo.userPassword) &&
        Objects.equals(this.userPassNote, accessInfo.userPassNote) &&
        Objects.equals(this.ipAddressRegMethod, accessInfo.ipAddressRegMethod) &&
        Objects.equals(this.ipAddressRegInstructions, accessInfo.ipAddressRegInstructions) &&
        Objects.equals(this.ipAddressNote, accessInfo.ipAddressNote) &&
        Objects.equals(this.accessNote, accessInfo.accessNote) &&
        Objects.equals(this.primaryAccessUri, accessInfo.primaryAccessUri) &&
        Objects.equals(this.interfaceUri, accessInfo.interfaceUri) &&
        Objects.equals(this.implementedAuthMethod, accessInfo.implementedAuthMethod) &&
        Objects.equals(this.localPersistentUri, accessInfo.localPersistentUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, userPassword, userPassNote, ipAddressRegMethod, ipAddressRegInstructions, ipAddressNote, accessNote, primaryAccessUri, interfaceUri, implementedAuthMethod, localPersistentUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessInfo2 {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    userPassword: ").append(toIndentedString(userPassword)).append("\n");
    sb.append("    userPassNote: ").append(toIndentedString(userPassNote)).append("\n");
    sb.append("    ipAddressRegMethod: ").append(toIndentedString(ipAddressRegMethod)).append("\n");
    sb.append("    ipAddressRegInstructions: ").append(toIndentedString(ipAddressRegInstructions)).append("\n");
    sb.append("    ipAddressNote: ").append(toIndentedString(ipAddressNote)).append("\n");
    sb.append("    accessNote: ").append(toIndentedString(accessNote)).append("\n");
    sb.append("    primaryAccessUri: ").append(toIndentedString(primaryAccessUri)).append("\n");
    sb.append("    interfaceUri: ").append(toIndentedString(interfaceUri)).append("\n");
    sb.append("    implementedAuthMethod: ").append(toIndentedString(implementedAuthMethod)).append("\n");
    sb.append("    localPersistentUri: ").append(toIndentedString(localPersistentUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

