/*
 * Ex Libris APIs
 * For more information on how to use these APIs, including how to create an API key required for authentication, see [Alma REST APIs](https://developers.exlibrisgroup.com/alma/apis).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.unidue.ub.alma.shared.acq;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import javax.xml.bind.annotation.*;

/**
 * A specific vendor account.
 */
@ApiModel(description = "A specific vendor account.")
@JsonPropertyOrder({
  Account.JSON_PROPERTY_CODE,
  Account.JSON_PROPERTY_DESCRIPTION,
  Account.JSON_PROPERTY_FINANCIAL_SYS_CODE,
  Account.JSON_PROPERTY_STATUS,
  Account.JSON_PROPERTY_LIBRARY,
  Account.JSON_PROPERTY_DISCOUNT_PERCENT,
  Account.JSON_PROPERTY_NOTE,
  Account.JSON_PROPERTY_PAYMENT_METHOD,
  Account.JSON_PROPERTY_EXPECTED_RECEIPT_INTERVAL,
  Account.JSON_PROPERTY_CLAIMING_INTERVAL,
  Account.JSON_PROPERTY_EXPECTED_INVOICE_INTERVAL,
  Account.JSON_PROPERTY_EXPECTED_ACTIVATION_INTERVAL,
  Account.JSON_PROPERTY_RENEWAL_EVALUATION_INTERVAL,
  Account.JSON_PROPERTY_SUBSCRIPTION_INTERVAL,
  Account.JSON_PROPERTY_RECLAIM_INTERVAL,
  Account.JSON_PROPERTY_CONTACT_INFO
})

@XmlRootElement(name = "account")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "account")
public class Account implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CODE = "code";
  @XmlElement(name = "code")
  private String code;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @XmlElement(name = "description")
  private String description;

  public static final String JSON_PROPERTY_FINANCIAL_SYS_CODE = "financial_sys_code";
  @XmlElement(name = "financial_sys_code")
  private String financialSysCode;

  public static final String JSON_PROPERTY_STATUS = "status";
  @XmlElement(name = "status")
  private AccountStatus status;

  public static final String JSON_PROPERTY_LIBRARY = "library";
  // Is a container wrapped=true
  // items.name=library items.baseName=library items.xmlName= items.xmlNamespace=
  // items.example= items.type=Library2
  @XmlElement(name = "library")
  @XmlElementWrapper(name = "libraries")
  private List<Library> library = null;

  public static final String JSON_PROPERTY_DISCOUNT_PERCENT = "discount_percent";
  @XmlElement(name = "discount_percent")
  private String discountPercent;

  public static final String JSON_PROPERTY_NOTE = "note";
  @XmlElement(name = "note")
  private String note;

  public static final String JSON_PROPERTY_PAYMENT_METHOD = "payment_method";
  // Is a container wrapped=true
  // items.name=paymentMethod items.baseName=paymentMethod items.xmlName=payment_method items.xmlNamespace=
  // items.example= items.type=Object
  @XmlElement(name = "payment_method")
  @XmlElementWrapper(name = "payment_methods")
  private List<InvoicePaymentMethod> paymentMethod = null;

  public static final String JSON_PROPERTY_EXPECTED_RECEIPT_INTERVAL = "expected_receipt_interval";
  @XmlElement(name = "expected_receipt_interval")
  private String expectedReceiptInterval;

  public static final String JSON_PROPERTY_CLAIMING_INTERVAL = "claiming_interval";
  @XmlElement(name = "claiming_interval")
  private String claimingInterval;

  public static final String JSON_PROPERTY_EXPECTED_INVOICE_INTERVAL = "expected_invoice_interval";
  @XmlElement(name = "expected_invoice_interval")
  private String expectedInvoiceInterval;

  public static final String JSON_PROPERTY_EXPECTED_ACTIVATION_INTERVAL = "expected_activation_interval";
  @XmlElement(name = "expected_activation_interval")
  private String expectedActivationInterval;

  public static final String JSON_PROPERTY_RENEWAL_EVALUATION_INTERVAL = "renewal_evaluation_interval";
  @XmlElement(name = "renewal_evaluation_interval")
  private String renewalEvaluationInterval;

  public static final String JSON_PROPERTY_SUBSCRIPTION_INTERVAL = "subscription_interval";
  @XmlElement(name = "subscription_interval")
  private String subscriptionInterval;

  public static final String JSON_PROPERTY_RECLAIM_INTERVAL = "reclaim_interval";
  @XmlElement(name = "reclaim_interval")
  private String reclaimInterval;

  public static final String JSON_PROPERTY_CONTACT_INFO = "contact_info";
  @XmlElement(name = "contact_info")
  private ContactInfo contactInfo;


  public Account code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * A code for the account. Mandatory.
   * @return code
  **/
  @ApiModelProperty(required = true, value = "A code for the account. Mandatory.")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  @JacksonXmlProperty(localName = "code")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public Account description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * A description for the account. Mandatory.
   * @return description
  **/
  @ApiModelProperty(required = true, value = "A description for the account. Mandatory.")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  @JacksonXmlProperty(localName = "description")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public Account financialSysCode(String financialSysCode) {
    
    this.financialSysCode = financialSysCode;
    return this;
  }

   /**
   * A code for the financial system account.
   * @return financialSysCode
  **/

  @ApiModelProperty(value = "A code for the financial system account.")
  @JsonProperty(JSON_PROPERTY_FINANCIAL_SYS_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "financial_sys_code")

  public String getFinancialSysCode() {
    return financialSysCode;
  }


  public void setFinancialSysCode(String financialSysCode) {
    this.financialSysCode = financialSysCode;
  }


  public Account status(AccountStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "status")

  public AccountStatus getStatus() {
    return status;
  }


  public void setStatus(AccountStatus status) {
    this.status = status;
  }


  public Account library(List<Library> library) {
    
    this.library = library;
    return this;
  }

  public Account addLibraryItem(Library libraryItem) {
    if (this.library == null) {
      this.library = new ArrayList<Library>();
    }
    this.library.add(libraryItem);
    return this;
  }

   /**
   * List of libraries related to the vendor or the account. If not specified, the default will be the institution including all sub units.
   * @return library
  **/

  @ApiModelProperty(value = "List of libraries related to the vendor or the account. If not specified, the default will be the institution including all sub units.")
  @JsonProperty(JSON_PROPERTY_LIBRARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=
  @JacksonXmlElementWrapper(useWrapping = true, localName = "library")

  public List<Library> getLibrary() {
    return library;
  }


  public void setLibrary(List<Library> library) {
    this.library = library;
  }


  public Account discountPercent(String discountPercent) {
    
    this.discountPercent = discountPercent;
    return this;
  }

   /**
   * A discount percentage for the account.
   * @return discountPercent
  **/

  @ApiModelProperty(value = "A discount percentage for the account.")
  @JsonProperty(JSON_PROPERTY_DISCOUNT_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "discount_percent")

  public String getDiscountPercent() {
    return discountPercent;
  }


  public void setDiscountPercent(String discountPercent) {
    this.discountPercent = discountPercent;
  }


  public Account note(String note) {
    
    this.note = note;
    return this;
  }

   /**
   * A note for the account.
   * @return note
  **/

  @ApiModelProperty(value = "A note for the account.")
  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "note")

  public String getNote() {
    return note;
  }


  public void setNote(String note) {
    this.note = note;
  }


  public Account paymentMethod(List<InvoicePaymentMethod> paymentMethod) {
    
    this.paymentMethod = paymentMethod;
    return this;
  }

  public Account addPaymentMethodItem(InvoicePaymentMethod paymentMethodItem) {
    if (this.paymentMethod == null) {
      this.paymentMethod = new ArrayList<>();
    }
    this.paymentMethod.add(paymentMethodItem);
    return this;
  }

   /**
   * List of supported payment methods.
   * @return paymentMethod
  **/

  @ApiModelProperty(value = "List of supported payment methods.")
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=payment_method
  @JacksonXmlElementWrapper(useWrapping = true, localName = "payment_method")

  public List<InvoicePaymentMethod> getPaymentMethod() {
    return paymentMethod;
  }


  public void setPaymentMethod(List<InvoicePaymentMethod> paymentMethod) {
    this.paymentMethod = paymentMethod;
  }


  public Account expectedReceiptInterval(String expectedReceiptInterval) {
    
    this.expectedReceiptInterval = expectedReceiptInterval;
    return this;
  }

   /**
   * When creating a PO line for a physical resource, this value appears by default in the same field on the PO Line Summary page. It is added to the current date to determine the expected receipt date.
   * @return expectedReceiptInterval
  **/

  @ApiModelProperty(value = "When creating a PO line for a physical resource, this value appears by default in the same field on the PO Line Summary page. It is added to the current date to determine the expected receipt date.")
  @JsonProperty(JSON_PROPERTY_EXPECTED_RECEIPT_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "expected_receipt_interval")

  public String getExpectedReceiptInterval() {
    return expectedReceiptInterval;
  }


  public void setExpectedReceiptInterval(String expectedReceiptInterval) {
    this.expectedReceiptInterval = expectedReceiptInterval;
  }


  public Account claimingInterval(String claimingInterval) {
    
    this.claimingInterval = claimingInterval;
    return this;
  }

   /**
   * When creating a PO line, this value appears by default in the same field on the PO Line Summary page. It is added to the expected receipt date to determine when a PO line is sent to the Claims task list.
   * @return claimingInterval
  **/

  @ApiModelProperty(value = "When creating a PO line, this value appears by default in the same field on the PO Line Summary page. It is added to the expected receipt date to determine when a PO line is sent to the Claims task list.")
  @JsonProperty(JSON_PROPERTY_CLAIMING_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "claiming_interval")

  public String getClaimingInterval() {
    return claimingInterval;
  }


  public void setClaimingInterval(String claimingInterval) {
    this.claimingInterval = claimingInterval;
  }


  public Account expectedInvoiceInterval(String expectedInvoiceInterval) {
    
    this.expectedInvoiceInterval = expectedInvoiceInterval;
    return this;
  }

   /**
   * Currently not in use.
   * @return expectedInvoiceInterval
  **/

  @ApiModelProperty(value = "Currently not in use.")
  @JsonProperty(JSON_PROPERTY_EXPECTED_INVOICE_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "expected_invoice_interval")

  public String getExpectedInvoiceInterval() {
    return expectedInvoiceInterval;
  }


  public void setExpectedInvoiceInterval(String expectedInvoiceInterval) {
    this.expectedInvoiceInterval = expectedInvoiceInterval;
  }


  public Account expectedActivationInterval(String expectedActivationInterval) {
    
    this.expectedActivationInterval = expectedActivationInterval;
    return this;
  }

   /**
   * hen creating a PO line for an e-resource, this value appears by default in the same field on the PO Line Summary page. It is added to the current date to determine the expected activation date of the resource.
   * @return expectedActivationInterval
  **/

  @ApiModelProperty(value = "hen creating a PO line for an e-resource, this value appears by default in the same field on the PO Line Summary page. It is added to the current date to determine the expected activation date of the resource.")
  @JsonProperty(JSON_PROPERTY_EXPECTED_ACTIVATION_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "expected_activation_interval")

  public String getExpectedActivationInterval() {
    return expectedActivationInterval;
  }


  public void setExpectedActivationInterval(String expectedActivationInterval) {
    this.expectedActivationInterval = expectedActivationInterval;
  }


  public Account renewalEvaluationInterval(String renewalEvaluationInterval) {
    
    this.renewalEvaluationInterval = renewalEvaluationInterval;
    return this;
  }

   /**
   * The number of days after the evaluation period that renewal can be performed.
   * @return renewalEvaluationInterval
  **/

  @ApiModelProperty(value = "The number of days after the evaluation period that renewal can be performed.")
  @JsonProperty(JSON_PROPERTY_RENEWAL_EVALUATION_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "renewal_evaluation_interval")

  public String getRenewalEvaluationInterval() {
    return renewalEvaluationInterval;
  }


  public void setRenewalEvaluationInterval(String renewalEvaluationInterval) {
    this.renewalEvaluationInterval = renewalEvaluationInterval;
  }


  public Account subscriptionInterval(String subscriptionInterval) {
    
    this.subscriptionInterval = subscriptionInterval;
    return this;
  }

   /**
   * When creating a PO line, this value appears by default in the Claiming grace period field on the PO Line Summary page. It is added to the expected activation date to determine when a PO line for an e-resource is sent to the Claims task list.
   * @return subscriptionInterval
  **/

  @ApiModelProperty(value = "When creating a PO line, this value appears by default in the Claiming grace period field on the PO Line Summary page. It is added to the expected activation date to determine when a PO line for an e-resource is sent to the Claims task list.")
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "subscription_interval")

  public String getSubscriptionInterval() {
    return subscriptionInterval;
  }


  public void setSubscriptionInterval(String subscriptionInterval) {
    this.subscriptionInterval = subscriptionInterval;
  }


  public Account reclaimInterval(String reclaimInterval) {
    
    this.reclaimInterval = reclaimInterval;
    return this;
  }

   /**
   * When creating a PO line, this value appears by default in the Reclaim interval field on the PO Line Summary page. The number of days to wait before sending a 2nd, 3rd, 4th etc claim letter to the vendor. Optional. Default: 0.
   * @return reclaimInterval
  **/
  @ApiModelProperty(example = "1", required = true, value = "When creating a PO line, this value appears by default in the Reclaim interval field on the PO Line Summary page. The number of days to wait before sending a 2nd, 3rd, 4th etc claim letter to the vendor. Optional. Default: 0.")
  @JsonProperty(JSON_PROPERTY_RECLAIM_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  @JacksonXmlProperty(localName = "reclaim_interval")

  public String getReclaimInterval() {
    return reclaimInterval;
  }


  public void setReclaimInterval(String reclaimInterval) {
    this.reclaimInterval = reclaimInterval;
  }


  public Account contactInfo(ContactInfo contactInfo) {
    
    this.contactInfo = contactInfo;
    return this;
  }

   /**
   * Get contactInfo
   * @return contactInfo
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTACT_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "contact_info")

  public ContactInfo getContactInfo() {
    return contactInfo;
  }


  public void setContactInfo(ContactInfo contactInfo) {
    this.contactInfo = contactInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return Objects.equals(this.code, account.code) &&
        Objects.equals(this.description, account.description) &&
        Objects.equals(this.financialSysCode, account.financialSysCode) &&
        Objects.equals(this.status, account.status) &&
        Objects.equals(this.library, account.library) &&
        Objects.equals(this.discountPercent, account.discountPercent) &&
        Objects.equals(this.note, account.note) &&
        Objects.equals(this.paymentMethod, account.paymentMethod) &&
        Objects.equals(this.expectedReceiptInterval, account.expectedReceiptInterval) &&
        Objects.equals(this.claimingInterval, account.claimingInterval) &&
        Objects.equals(this.expectedInvoiceInterval, account.expectedInvoiceInterval) &&
        Objects.equals(this.expectedActivationInterval, account.expectedActivationInterval) &&
        Objects.equals(this.renewalEvaluationInterval, account.renewalEvaluationInterval) &&
        Objects.equals(this.subscriptionInterval, account.subscriptionInterval) &&
        Objects.equals(this.reclaimInterval, account.reclaimInterval) &&
        Objects.equals(this.contactInfo, account.contactInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, description, financialSysCode, status, library, discountPercent, note, paymentMethod, expectedReceiptInterval, claimingInterval, expectedInvoiceInterval, expectedActivationInterval, renewalEvaluationInterval, subscriptionInterval, reclaimInterval, contactInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account2 {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    financialSysCode: ").append(toIndentedString(financialSysCode)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    library: ").append(toIndentedString(library)).append("\n");
    sb.append("    discountPercent: ").append(toIndentedString(discountPercent)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    expectedReceiptInterval: ").append(toIndentedString(expectedReceiptInterval)).append("\n");
    sb.append("    claimingInterval: ").append(toIndentedString(claimingInterval)).append("\n");
    sb.append("    expectedInvoiceInterval: ").append(toIndentedString(expectedInvoiceInterval)).append("\n");
    sb.append("    expectedActivationInterval: ").append(toIndentedString(expectedActivationInterval)).append("\n");
    sb.append("    renewalEvaluationInterval: ").append(toIndentedString(renewalEvaluationInterval)).append("\n");
    sb.append("    subscriptionInterval: ").append(toIndentedString(subscriptionInterval)).append("\n");
    sb.append("    reclaimInterval: ").append(toIndentedString(reclaimInterval)).append("\n");
    sb.append("    contactInfo: ").append(toIndentedString(contactInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

