/*
 * Ex Libris APIs
 * For more information on how to use these APIs, including how to create an API key required for authentication, see [Alma REST APIs](https://developers.exlibrisgroup.com/alma/apis).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.unidue.ub.alma.shared.acq;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import javax.xml.bind.annotation.*;

/**
 * Specific administrator.
 */
@ApiModel(description = "Specific administrator.")
@JsonPropertyOrder({
  Administrator.JSON_PROPERTY_LINK,
  Administrator.JSON_PROPERTY_PRIMARY_ID,
  Administrator.JSON_PROPERTY_FIRST_NAME,
  Administrator.JSON_PROPERTY_LAST_NAME,
  Administrator.JSON_PROPERTY_EMAIL
})

@XmlRootElement(name = "administrator")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "administrator")
public class Administrator implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_LINK = "link";
  @XmlAttribute(name = "link")
  private String link;

  public static final String JSON_PROPERTY_PRIMARY_ID = "primary_id";
  @XmlElement(name = "primary_id")
  private String primaryId;

  public static final String JSON_PROPERTY_FIRST_NAME = "first_name";
  @XmlElement(name = "first_name")
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "last_name";
  @XmlElement(name = "last_name")
  private String lastName;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @XmlElement(name = "email")
  private String email;


  public Administrator link(String link) {
    
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(isAttribute = true, localName = "link")

  public String getLink() {
    return link;
  }


  public void setLink(String link) {
    this.link = link;
  }


  public Administrator primaryId(String primaryId) {
    
    this.primaryId = primaryId;
    return this;
  }

   /**
   * Administrator&#39;s primary identifier.
   * @return primaryId
  **/

  @ApiModelProperty(example = "134099884231021", value = "Administrator's primary identifier.")
  @JsonProperty(JSON_PROPERTY_PRIMARY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "primary_id")

  public String getPrimaryId() {
    return primaryId;
  }


  public void setPrimaryId(String primaryId) {
    this.primaryId = primaryId;
  }


  public Administrator firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * Administrator&#39;s first name. Output parameter.
   * @return firstName
  **/

  @ApiModelProperty(example = "John", value = "Administrator's first name. Output parameter.")
  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "first_name")

  public String getFirstName() {
    return firstName;
  }


  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public Administrator lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Administrator&#39;s last name. Output parameter.
   * @return lastName
  **/

  @ApiModelProperty(example = "Smith", value = "Administrator's last name. Output parameter.")
  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "last_name")

  public String getLastName() {
    return lastName;
  }


  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public Administrator email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Administrator&#39;s preferred email address. Output parameter.
   * @return email
  **/

  @ApiModelProperty(example = "jsmith@gmail.com", value = "Administrator's preferred email address. Output parameter.")
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "email")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Administrator administrator = (Administrator) o;
    return Objects.equals(this.link, administrator.link) &&
        Objects.equals(this.primaryId, administrator.primaryId) &&
        Objects.equals(this.firstName, administrator.firstName) &&
        Objects.equals(this.lastName, administrator.lastName) &&
        Objects.equals(this.email, administrator.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(link, primaryId, firstName, lastName, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Administrator2 {\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    primaryId: ").append(toIndentedString(primaryId)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

