/*
 * Ex Libris APIs
 * For more information on how to use these APIs, including how to create an API key required for authentication, see [Alma REST APIs](https://developers.exlibrisgroup.com/alma/apis).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.unidue.ub.alma.shared.acq;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import javax.xml.bind.annotation.*;

/**
 * Fund Object.
 */
@ApiModel(description = "Fund Object.")
@JsonPropertyOrder({
  Fund.JSON_PROPERTY_LINK,
  Fund.JSON_PROPERTY_ID,
  Fund.JSON_PROPERTY_CODE,
  Fund.JSON_PROPERTY_NAME,
  Fund.JSON_PROPERTY_EXTERNAL_ID,
  Fund.JSON_PROPERTY_TYPE,
  Fund.JSON_PROPERTY_STATUS,
  Fund.JSON_PROPERTY_DESCRIPTION,
  Fund.JSON_PROPERTY_FISCAL_PERIOD,
  Fund.JSON_PROPERTY_CURRENCY,
  Fund.JSON_PROPERTY_AVAILABLE_BALANCE
})

@XmlRootElement(name = "fund")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "fund")
public class Fund implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_LINK = "link";
  @XmlAttribute(name = "link")
  private String link;

  public static final String JSON_PROPERTY_ID = "id";
  @XmlElement(name = "id")
  private String id;

  public static final String JSON_PROPERTY_CODE = "code";
  @XmlElement(name = "code")
  private String code;

  public static final String JSON_PROPERTY_NAME = "name";
  @XmlElement(name = "name")
  private String name;

  public static final String JSON_PROPERTY_EXTERNAL_ID = "external_id";
  @XmlElement(name = "external_id")
  private String externalId;

  public static final String JSON_PROPERTY_TYPE = "type";
  @XmlElement(name = "type")
  private FundType type;

  public static final String JSON_PROPERTY_STATUS = "status";
  @XmlElement(name = "status")
  private FundStatus status;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @XmlElement(name = "description")
  private String description;

  public static final String JSON_PROPERTY_FISCAL_PERIOD = "fiscal_period";
  @XmlElement(name = "fiscal_period")
  private FundFiscalPeriod fiscalPeriod;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @XmlElement(name = "currency")
  private FundCurrency currency;

  public static final String JSON_PROPERTY_AVAILABLE_BALANCE = "available_balance";
  @XmlElement(name = "available_balance")
  private String availableBalance;


  public Fund link(String link) {
    
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(isAttribute = true, localName = "link")

  public String getLink() {
    return link;
  }


  public void setLink(String link) {
    this.link = link;
  }


  public Fund id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Identifier of the fund in Alma. Output parameter. Should be used in subsequent queries regarding the fund.
   * @return id
  **/
  
  @ApiModelProperty(example = "1239410001021", value = "Identifier of the fund in Alma. Output parameter. Should be used in subsequent queries regarding the fund.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "id")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Fund code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * The fund code.
   * @return code
  **/
  @ApiModelProperty(example = "BIO", required = true, value = "The fund code.")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  @JacksonXmlProperty(localName = "code")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public Fund name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The fund name.
   * @return name
  **/
  
  @ApiModelProperty(example = "Biology", value = "The fund name.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Fund externalId(String externalId) {
    
    this.externalId = externalId;
    return this;
  }

   /**
   * The ID that is used to link to other system keys.
   * @return externalId
  **/
  
  @ApiModelProperty(example = "1239410001021", value = "The ID that is used to link to other system keys.")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "external_id")

  public String getExternalId() {
    return externalId;
  }


  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }


  public Fund type(FundType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "type")

  public FundType getType() {
    return type;
  }


  public void setType(FundType type) {
    this.type = type;
  }


  public Fund status(FundStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "status")

  public FundStatus getStatus() {
    return status;
  }


  public void setStatus(FundStatus status) {
    this.status = status;
  }


  public Fund description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * General description of the fund.
   * @return description
  **/
  
  @ApiModelProperty(example = "desc", value = "General description of the fund.")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "description")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public Fund fiscalPeriod(FundFiscalPeriod fiscalPeriod) {
    
    this.fiscalPeriod = fiscalPeriod;
    return this;
  }

   /**
   * Get fiscalPeriod
   * @return fiscalPeriod
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FISCAL_PERIOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  @JacksonXmlProperty(localName = "fiscal_period")

  public FundFiscalPeriod getFiscalPeriod() {
    return fiscalPeriod;
  }


  public void setFiscalPeriod(FundFiscalPeriod fiscalPeriod) {
    this.fiscalPeriod = fiscalPeriod;
  }


  public Fund currency(FundCurrency currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "currency")

  public FundCurrency getCurrency() {
    return currency;
  }


  public void setCurrency(FundCurrency currency) {
    this.currency = currency;
  }


  public Fund availableBalance(String availableBalance) {
    
    this.availableBalance = availableBalance;
    return this;
  }

   /**
   * A fund&#39;s available balance is its allocated balance, less (encumbrances minus disencumbrances) and less expenditures.
   * @return availableBalance
  **/
  
  @ApiModelProperty(example = "94155.42", value = "A fund's available balance is its allocated balance, less (encumbrances minus disencumbrances) and less expenditures.")
  @JsonProperty(JSON_PROPERTY_AVAILABLE_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "available_balance")

  public String getAvailableBalance() {
    return availableBalance;
  }


  public void setAvailableBalance(String availableBalance) {
    this.availableBalance = availableBalance;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fund fund = (Fund) o;
    return Objects.equals(this.link, fund.link) &&
        Objects.equals(this.id, fund.id) &&
        Objects.equals(this.code, fund.code) &&
        Objects.equals(this.name, fund.name) &&
        Objects.equals(this.externalId, fund.externalId) &&
        Objects.equals(this.type, fund.type) &&
        Objects.equals(this.status, fund.status) &&
        Objects.equals(this.description, fund.description) &&
        Objects.equals(this.fiscalPeriod, fund.fiscalPeriod) &&
        Objects.equals(this.currency, fund.currency) &&
        Objects.equals(this.availableBalance, fund.availableBalance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(link, id, code, name, externalId, type, status, description, fiscalPeriod, currency, availableBalance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fund {\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    fiscalPeriod: ").append(toIndentedString(fiscalPeriod)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    availableBalance: ").append(toIndentedString(availableBalance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

