/*
 * Ex Libris APIs
 * For more information on how to use these APIs, including how to create an API key required for authentication, see [Alma REST APIs](https://developers.exlibrisgroup.com/alma/apis).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.unidue.ub.alma.shared.acq;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import javax.xml.bind.annotation.*;

/**
 * VAT charge that is included in the invoice line. Relevant only if the invoice is defined as &#39;vat_per_invoice_line&#39;.
 */
@ApiModel(description = "VAT charge that is included in the invoice line. Relevant only if the invoice is defined as 'vat_per_invoice_line'.")
@JsonPropertyOrder({
  InvoiceLineVat.JSON_PROPERTY_VAT_CODE,
  InvoiceLineVat.JSON_PROPERTY_PERCENTAGE,
  InvoiceLineVat.JSON_PROPERTY_VAT_AMOUNT
})

@XmlRootElement(name = "invoice_line_vat")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "invoice_line_vat")
public class InvoiceLineVat implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_VAT_CODE = "vat_code";
  @XmlElement(name = "vat_code")
  private InvoiceLineVatVatCode vatCode;

  public static final String JSON_PROPERTY_PERCENTAGE = "percentage";
  @XmlElement(name = "percentage")
  private Double percentage;

  public static final String JSON_PROPERTY_VAT_AMOUNT = "vat_amount";
  @XmlElement(name = "vat_amount")
  private Double vatAmount;


  public InvoiceLineVat vatCode(InvoiceLineVatVatCode vatCode) {
    
    this.vatCode = vatCode;
    return this;
  }

   /**
   * Get vatCode
   * @return vatCode
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "vat_code")

  public InvoiceLineVatVatCode getVatCode() {
    return vatCode;
  }


  public void setVatCode(InvoiceLineVatVatCode vatCode) {
    this.vatCode = vatCode;
  }


  public InvoiceLineVat percentage(Double percentage) {
    
    this.percentage = percentage;
    return this;
  }

   /**
   * VAT Percentage of the invoice line price. In POST and PUT actions, percentage or vat_amount should be supplied, but not both. If vat_code is defined, percentage and vat_amount should be left empty in these actions.
   * @return percentage
  **/

  @ApiModelProperty(example = "0.00", value = "VAT Percentage of the invoice line price. In POST and PUT actions, percentage or vat_amount should be supplied, but not both. If vat_code is defined, percentage and vat_amount should be left empty in these actions.")
  @JsonProperty(JSON_PROPERTY_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "percentage")

  public Double getPercentage() {
    return percentage;
  }


  public void setPercentage(Double percentage) {
    this.percentage = percentage;
  }


  public InvoiceLineVat vatAmount(Double vatAmount) {
    
    this.vatAmount = vatAmount;
    return this;
  }

   /**
   * Amount of VAT to be paid on the invoice line. In POST and PUT actions, percentage or vat_amount should be supplied, but not both. If vat_code is defined, percentage and vat_amount should be left empty in these actions.
   * @return vatAmount
  **/

  @ApiModelProperty(example = "0", value = "Amount of VAT to be paid on the invoice line. In POST and PUT actions, percentage or vat_amount should be supplied, but not both. If vat_code is defined, percentage and vat_amount should be left empty in these actions.")
  @JsonProperty(JSON_PROPERTY_VAT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "vat_amount")

  public Double getVatAmount() {
    return vatAmount;
  }


  public void setVatAmount(Double vatAmount) {
    this.vatAmount = vatAmount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoiceLineVat invoiceLineVat = (InvoiceLineVat) o;
    return Objects.equals(this.vatCode, invoiceLineVat.vatCode) &&
        Objects.equals(this.percentage, invoiceLineVat.percentage) &&
        Objects.equals(this.vatAmount, invoiceLineVat.vatAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vatCode, percentage, vatAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoiceLineVat2 {\n");
    sb.append("    vatCode: ").append(toIndentedString(vatCode)).append("\n");
    sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
    sb.append("    vatAmount: ").append(toIndentedString(vatAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

