/*
 * Ex Libris APIs
 * For more information on how to use these APIs, including how to create an API key required for authentication, see [Alma REST APIs](https://developers.exlibrisgroup.com/alma/apis).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.unidue.ub.alma.shared.acq;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import javax.xml.bind.annotation.*;

/**
 * A Physical item.
 */
@ApiModel(description = "A Physical item.")
@JsonPropertyOrder({
  Item.JSON_PROPERTY_LINK,
  Item.JSON_PROPERTY_BIB_DATA,
  Item.JSON_PROPERTY_HOLDING_DATA,
  Item.JSON_PROPERTY_ITEM_DATA,
  Item.JSON_PROPERTY_ADDITIONAL_INFO
})

@XmlRootElement(name = "item")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "item")
public class Item implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_LINK = "link";
  @XmlAttribute(name = "link")
  private String link;

  public static final String JSON_PROPERTY_BIB_DATA = "bib_data";
  @XmlElement(name = "bib_data")
  private BibData bibData;

  public static final String JSON_PROPERTY_HOLDING_DATA = "holding_data";
  @XmlElement(name = "holding_data")
  private HoldingData holdingData;

  public static final String JSON_PROPERTY_ITEM_DATA = "item_data";
  @XmlElement(name = "item_data")
  private ItemData itemData;

  public static final String JSON_PROPERTY_ADDITIONAL_INFO = "additional_info";
  @XmlElement(name = "additional_info")
  private String additionalInfo;


  public Item link(String link) {
    
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(isAttribute = true, localName = "link")

  public String getLink() {
    return link;
  }


  public void setLink(String link) {
    this.link = link;
  }


  public Item bibData(BibData bibData) {
    
    this.bibData = bibData;
    return this;
  }

   /**
   * Get bibData
   * @return bibData
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BIB_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "bib_data")

  public BibData getBibData() {
    return bibData;
  }


  public void setBibData(BibData bibData) {
    this.bibData = bibData;
  }


  public Item holdingData(HoldingData holdingData) {
    
    this.holdingData = holdingData;
    return this;
  }

   /**
   * Get holdingData
   * @return holdingData
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_HOLDING_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  @JacksonXmlProperty(localName = "holding_data")

  public HoldingData getHoldingData() {
    return holdingData;
  }


  public void setHoldingData(HoldingData holdingData) {
    this.holdingData = holdingData;
  }


  public Item itemData(ItemData itemData) {
    
    this.itemData = itemData;
    return this;
  }

   /**
   * Get itemData
   * @return itemData
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ITEM_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  @JacksonXmlProperty(localName = "item_data")

  public ItemData getItemData() {
    return itemData;
  }


  public void setItemData(ItemData itemData) {
    this.itemData = itemData;
  }


  public Item additionalInfo(String additionalInfo) {
    
    this.additionalInfo = additionalInfo;
    return this;
  }

   /**
   * Additional information following an action on the item. Output parameter.
   * @return additionalInfo
  **/
  
  @ApiModelProperty(value = "Additional information following an action on the item. Output parameter.")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "additional_info")

  public String getAdditionalInfo() {
    return additionalInfo;
  }


  public void setAdditionalInfo(String additionalInfo) {
    this.additionalInfo = additionalInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Item item = (Item) o;
    return Objects.equals(this.link, item.link) &&
        Objects.equals(this.bibData, item.bibData) &&
        Objects.equals(this.holdingData, item.holdingData) &&
        Objects.equals(this.itemData, item.itemData) &&
        Objects.equals(this.additionalInfo, item.additionalInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(link, bibData, holdingData, itemData, additionalInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Item2 {\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    bibData: ").append(toIndentedString(bibData)).append("\n");
    sb.append("    holdingData: ").append(toIndentedString(holdingData)).append("\n");
    sb.append("    itemData: ").append(toIndentedString(itemData)).append("\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

