/*
 * Ex Libris APIs
 * For more information on how to use these APIs, including how to create an API key required for authentication, see [Alma REST APIs](https://developers.exlibrisgroup.com/alma/apis).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.unidue.ub.alma.shared.acq;

import java.time.OffsetDateTime;
import java.util.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import javax.xml.bind.annotation.*;

/**
 * Physical Item data.
 */
@ApiModel(description = "Physical Item data.")
@JsonPropertyOrder({
  ItemData.JSON_PROPERTY_PID,
  ItemData.JSON_PROPERTY_BARCODE,
  ItemData.JSON_PROPERTY_CREATION_DATE,
  ItemData.JSON_PROPERTY_MODIFICATION_DATE,
  ItemData.JSON_PROPERTY_BASE_STATUS,
  ItemData.JSON_PROPERTY_AWAITING_RESHELVING,
  ItemData.JSON_PROPERTY_RESHELVING_TIME,
  ItemData.JSON_PROPERTY_PHYSICAL_MATERIAL_TYPE,
  ItemData.JSON_PROPERTY_POLICY,
  ItemData.JSON_PROPERTY_PROVENANCE,
  ItemData.JSON_PROPERTY_PO_LINE,
  ItemData.JSON_PROPERTY_IS_MAGNETIC,
  ItemData.JSON_PROPERTY_ARRIVAL_DATE,
  ItemData.JSON_PROPERTY_EXPECTED_ARRIVAL_DATE,
  ItemData.JSON_PROPERTY_YEAR_OF_ISSUE,
  ItemData.JSON_PROPERTY_ENUMERATION_A,
  ItemData.JSON_PROPERTY_ENUMERATION_B,
  ItemData.JSON_PROPERTY_ENUMERATION_C,
  ItemData.JSON_PROPERTY_ENUMERATION_D,
  ItemData.JSON_PROPERTY_ENUMERATION_E,
  ItemData.JSON_PROPERTY_ENUMERATION_F,
  ItemData.JSON_PROPERTY_ENUMERATION_G,
  ItemData.JSON_PROPERTY_ENUMERATION_H,
  ItemData.JSON_PROPERTY_CHRONOLOGY_I,
  ItemData.JSON_PROPERTY_CHRONOLOGY_J,
  ItemData.JSON_PROPERTY_CHRONOLOGY_K,
  ItemData.JSON_PROPERTY_CHRONOLOGY_L,
  ItemData.JSON_PROPERTY_CHRONOLOGY_M,
  ItemData.JSON_PROPERTY_DESCRIPTION,
  ItemData.JSON_PROPERTY_REPLACEMENT_COST,
  ItemData.JSON_PROPERTY_RECEIVING_OPERATOR,
  ItemData.JSON_PROPERTY_PROCESS_TYPE,
  ItemData.JSON_PROPERTY_WORK_ORDER_TYPE,
  ItemData.JSON_PROPERTY_WORK_ORDER_AT,
  ItemData.JSON_PROPERTY_INVENTORY_NUMBER,
  ItemData.JSON_PROPERTY_INVENTORY_DATE,
  ItemData.JSON_PROPERTY_INVENTORY_PRICE,
  ItemData.JSON_PROPERTY_RECEIVE_NUMBER,
  ItemData.JSON_PROPERTY_WEEDING_NUMBER,
  ItemData.JSON_PROPERTY_WEEDING_DATE,
  ItemData.JSON_PROPERTY_LIBRARY,
  ItemData.JSON_PROPERTY_LOCATION,
  ItemData.JSON_PROPERTY_ALTERNATIVE_CALL_NUMBER,
  ItemData.JSON_PROPERTY_ALTERNATIVE_CALL_NUMBER_TYPE,
  ItemData.JSON_PROPERTY_ALT_NUMBER_SOURCE,
  ItemData.JSON_PROPERTY_STORAGE_LOCATION_ID,
  ItemData.JSON_PROPERTY_PAGES,
  ItemData.JSON_PROPERTY_PIECES,
  ItemData.JSON_PROPERTY_PUBLIC_NOTE,
  ItemData.JSON_PROPERTY_FULFILLMENT_NOTE,
  ItemData.JSON_PROPERTY_DUE_DATE,
  ItemData.JSON_PROPERTY_DUE_DATE_POLICY,
  ItemData.JSON_PROPERTY_INTERNAL_NOTE1,
  ItemData.JSON_PROPERTY_INTERNAL_NOTE2,
  ItemData.JSON_PROPERTY_INTERNAL_NOTE3,
  ItemData.JSON_PROPERTY_STATISTICS_NOTE1,
  ItemData.JSON_PROPERTY_STATISTICS_NOTE2,
  ItemData.JSON_PROPERTY_STATISTICS_NOTE3,
  ItemData.JSON_PROPERTY_REQUESTED,
  ItemData.JSON_PROPERTY_EDITION,
  ItemData.JSON_PROPERTY_IMPRINT,
  ItemData.JSON_PROPERTY_LANGUAGE,
  ItemData.JSON_PROPERTY_LIBRARY_DETAILS,
  ItemData.JSON_PROPERTY_ALT_CALL_NO,
  ItemData.JSON_PROPERTY_CALL_NO,
  ItemData.JSON_PROPERTY_ISSUE_LEVEL_DESCRIPTION,
  ItemData.JSON_PROPERTY_TITLE_ABCNPH,
  ItemData.JSON_PROPERTY_PHYSICAL_CONDITION
})

@XmlRootElement(name = "item_data")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "item_data")
public class ItemData implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_PID = "pid";
  @XmlElement(name = "pid")
  private String pid;

  public static final String JSON_PROPERTY_BARCODE = "barcode";
  @XmlElement(name = "barcode")
  private String barcode;

  public static final String JSON_PROPERTY_CREATION_DATE = "creation_date";
  @XmlElement(name = "creation_date")
  private Date creationDate;

  public static final String JSON_PROPERTY_MODIFICATION_DATE = "modification_date";
  @XmlElement(name = "modification_date")
  private Date modificationDate;

  public static final String JSON_PROPERTY_BASE_STATUS = "base_status";
  @XmlElement(name = "base_status")
  private ItemDataBaseStatus baseStatus;

  public static final String JSON_PROPERTY_AWAITING_RESHELVING = "awaiting_reshelving";
  @XmlElement(name = "awaiting_reshelving")
  private Boolean awaitingReshelving;

  public static final String JSON_PROPERTY_RESHELVING_TIME = "reshelving_time";
  @XmlElement(name = "reshelving_time")
  private OffsetDateTime reshelvingTime;

  public static final String JSON_PROPERTY_PHYSICAL_MATERIAL_TYPE = "physical_material_type";
  @XmlElement(name = "physical_material_type")
  private ItemDataPhysicalMaterialType physicalMaterialType;

  public static final String JSON_PROPERTY_POLICY = "policy";
  @XmlElement(name = "policy")
  private ItemDataPolicy policy;

  public static final String JSON_PROPERTY_PROVENANCE = "provenance";
  @XmlElement(name = "provenance")
  private ItemDataProvenance provenance;

  public static final String JSON_PROPERTY_PO_LINE = "po_line";
  @XmlElement(name = "po_line")
  private String poLine;

  public static final String JSON_PROPERTY_IS_MAGNETIC = "is_magnetic";
  @XmlElement(name = "is_magnetic")
  private Boolean isMagnetic;

  public static final String JSON_PROPERTY_ARRIVAL_DATE = "arrival_date";
  @XmlElement(name = "arrival_date")
  private Date arrivalDate;

  public static final String JSON_PROPERTY_EXPECTED_ARRIVAL_DATE = "expected_arrival_date";
  @XmlElement(name = "expected_arrival_date")
  private Date expectedArrivalDate;

  public static final String JSON_PROPERTY_YEAR_OF_ISSUE = "year_of_issue";
  @XmlElement(name = "year_of_issue")
  private String yearOfIssue;

  public static final String JSON_PROPERTY_ENUMERATION_A = "enumeration_a";
  @XmlElement(name = "enumeration_a")
  private String enumerationA;

  public static final String JSON_PROPERTY_ENUMERATION_B = "enumeration_b";
  @XmlElement(name = "enumeration_b")
  private String enumerationB;

  public static final String JSON_PROPERTY_ENUMERATION_C = "enumeration_c";
  @XmlElement(name = "enumeration_c")
  private String enumerationC;

  public static final String JSON_PROPERTY_ENUMERATION_D = "enumeration_d";
  @XmlElement(name = "enumeration_d")
  private String enumerationD;

  public static final String JSON_PROPERTY_ENUMERATION_E = "enumeration_e";
  @XmlElement(name = "enumeration_e")
  private String enumerationE;

  public static final String JSON_PROPERTY_ENUMERATION_F = "enumeration_f";
  @XmlElement(name = "enumeration_f")
  private String enumerationF;

  public static final String JSON_PROPERTY_ENUMERATION_G = "enumeration_g";
  @XmlElement(name = "enumeration_g")
  private String enumerationG;

  public static final String JSON_PROPERTY_ENUMERATION_H = "enumeration_h";
  @XmlElement(name = "enumeration_h")
  private String enumerationH;

  public static final String JSON_PROPERTY_CHRONOLOGY_I = "chronology_i";
  @XmlElement(name = "chronology_i")
  private String chronologyI;

  public static final String JSON_PROPERTY_CHRONOLOGY_J = "chronology_j";
  @XmlElement(name = "chronology_j")
  private String chronologyJ;

  public static final String JSON_PROPERTY_CHRONOLOGY_K = "chronology_k";
  @XmlElement(name = "chronology_k")
  private String chronologyK;

  public static final String JSON_PROPERTY_CHRONOLOGY_L = "chronology_l";
  @XmlElement(name = "chronology_l")
  private String chronologyL;

  public static final String JSON_PROPERTY_CHRONOLOGY_M = "chronology_m";
  @XmlElement(name = "chronology_m")
  private String chronologyM;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @XmlElement(name = "description")
  private String description;

  public static final String JSON_PROPERTY_REPLACEMENT_COST = "replacement_cost";
  @XmlElement(name = "replacement_cost")
  private Float replacementCost;

  public static final String JSON_PROPERTY_RECEIVING_OPERATOR = "receiving_operator";
  @XmlElement(name = "receiving_operator")
  private String receivingOperator;

  public static final String JSON_PROPERTY_PROCESS_TYPE = "process_type";
  @XmlElement(name = "process_type")
  private ItemDataProcessType processType;

  public static final String JSON_PROPERTY_WORK_ORDER_TYPE = "work_order_type";
  @XmlElement(name = "work_order_type")
  private ItemDataWorkOrderType workOrderType;

  public static final String JSON_PROPERTY_WORK_ORDER_AT = "work_order_at";
  @XmlElement(name = "work_order_at")
  private ItemDataWorkOrderAt workOrderAt;

  public static final String JSON_PROPERTY_INVENTORY_NUMBER = "inventory_number";
  @XmlElement(name = "inventory_number")
  private String inventoryNumber;

  public static final String JSON_PROPERTY_INVENTORY_DATE = "inventory_date";
  @XmlElement(name = "inventory_date")
  private Date inventoryDate;

  public static final String JSON_PROPERTY_INVENTORY_PRICE = "inventory_price";
  @XmlElement(name = "inventory_price")
  private String inventoryPrice;

  public static final String JSON_PROPERTY_RECEIVE_NUMBER = "receive_number";
  @XmlElement(name = "receive_number")
  private String receiveNumber;

  public static final String JSON_PROPERTY_WEEDING_NUMBER = "weeding_number";
  @XmlElement(name = "weeding_number")
  private String weedingNumber;

  public static final String JSON_PROPERTY_WEEDING_DATE = "weeding_date";
  @XmlElement(name = "weeding_date")
  private Date weedingDate;

  public static final String JSON_PROPERTY_LIBRARY = "library";
  @XmlElement(name = "library")
  private ItemDataLibrary library;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @XmlElement(name = "location")
  private ItemDataLocation location;

  public static final String JSON_PROPERTY_ALTERNATIVE_CALL_NUMBER = "alternative_call_number";
  @XmlElement(name = "alternative_call_number")
  private String alternativeCallNumber;

  public static final String JSON_PROPERTY_ALTERNATIVE_CALL_NUMBER_TYPE = "alternative_call_number_type";
  @XmlElement(name = "alternative_call_number_type")
  private ItemDataAlternativeCallNumberType alternativeCallNumberType;

  public static final String JSON_PROPERTY_ALT_NUMBER_SOURCE = "alt_number_source";
  @XmlElement(name = "alt_number_source")
  private String altNumberSource;

  public static final String JSON_PROPERTY_STORAGE_LOCATION_ID = "storage_location_id";
  @XmlElement(name = "storage_location_id")
  private String storageLocationId;

  public static final String JSON_PROPERTY_PAGES = "pages";
  @XmlElement(name = "pages")
  private String pages;

  public static final String JSON_PROPERTY_PIECES = "pieces";
  @XmlElement(name = "pieces")
  private String pieces;

  public static final String JSON_PROPERTY_PUBLIC_NOTE = "public_note";
  @XmlElement(name = "public_note")
  private String publicNote;

  public static final String JSON_PROPERTY_FULFILLMENT_NOTE = "fulfillment_note";
  @XmlElement(name = "fulfillment_note")
  private String fulfillmentNote;

  public static final String JSON_PROPERTY_DUE_DATE = "due_date";
  @XmlElement(name = "due_date")
  private OffsetDateTime dueDate;

  public static final String JSON_PROPERTY_DUE_DATE_POLICY = "due_date_policy";
  @XmlElement(name = "due_date_policy")
  private String dueDatePolicy;

  public static final String JSON_PROPERTY_INTERNAL_NOTE1 = "internal_note_1";
  @XmlElement(name = "internal_note_1")
  private String internalNote1;

  public static final String JSON_PROPERTY_INTERNAL_NOTE2 = "internal_note_2";
  @XmlElement(name = "internal_note_2")
  private String internalNote2;

  public static final String JSON_PROPERTY_INTERNAL_NOTE3 = "internal_note_3";
  @XmlElement(name = "internal_note_3")
  private String internalNote3;

  public static final String JSON_PROPERTY_STATISTICS_NOTE1 = "statistics_note_1";
  @XmlElement(name = "statistics_note_1")
  private String statisticsNote1;

  public static final String JSON_PROPERTY_STATISTICS_NOTE2 = "statistics_note_2";
  @XmlElement(name = "statistics_note_2")
  private String statisticsNote2;

  public static final String JSON_PROPERTY_STATISTICS_NOTE3 = "statistics_note_3";
  @XmlElement(name = "statistics_note_3")
  private String statisticsNote3;

  public static final String JSON_PROPERTY_REQUESTED = "requested";
  @XmlElement(name = "requested")
  private Boolean requested;

  public static final String JSON_PROPERTY_EDITION = "edition";
  @XmlElement(name = "edition")
  private String edition;

  public static final String JSON_PROPERTY_IMPRINT = "imprint";
  @XmlElement(name = "imprint")
  private String imprint;

  public static final String JSON_PROPERTY_LANGUAGE = "language";
  @XmlElement(name = "language")
  private String language;

  public static final String JSON_PROPERTY_LIBRARY_DETAILS = "library_details";
  @XmlElement(name = "library_details")
  private LibraryDetails libraryDetails;

  public static final String JSON_PROPERTY_ALT_CALL_NO = "alt_call_no";
  // Is a container wrapped=true
  // items.name=altCallNo items.baseName=altCallNo items.xmlName=alt_call_no items.xmlNamespace=
  // items.example= items.type=String
  @XmlElement(name = "alt_call_no")
  @XmlElementWrapper(name = "parsed_alt_call_number")
  private List<String> altCallNo = null;

  public static final String JSON_PROPERTY_CALL_NO = "call_no";
  // Is a container wrapped=true
  // items.name=callNo items.baseName=callNo items.xmlName=call_no items.xmlNamespace=
  // items.example= items.type=String
  @XmlElement(name = "call_no")
  @XmlElementWrapper(name = "parsed_call_number")
  private List<String> callNo = null;

  public static final String JSON_PROPERTY_ISSUE_LEVEL_DESCRIPTION = "issue_level_description";
  // Is a container wrapped=true
  // items.name=issueLevelDescription items.baseName=issueLevelDescription items.xmlName=issue_level_description items.xmlNamespace=
  // items.example= items.type=String
  @XmlElement(name = "issue_level_description")
  @XmlElementWrapper(name = "parsed_issue_level_description")
  private List<String> issueLevelDescription = null;

  public static final String JSON_PROPERTY_TITLE_ABCNPH = "title_abcnph";
  @XmlElement(name = "title_abcnph")
  private String titleAbcnph;

  public static final String JSON_PROPERTY_PHYSICAL_CONDITION = "physical_condition";
  @XmlElement(name = "physical_condition")
  private ItemDataPhysicalCondition physicalCondition;


  public ItemData pid(String pid) {
    
    this.pid = pid;
    return this;
  }

   /**
   * Physical item pid. Output parameter.
   * @return pid
  **/
  
  @ApiModelProperty(example = "23344156380001021", value = "Physical item pid. Output parameter.")
  @JsonProperty(JSON_PROPERTY_PID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "pid")

  public String getPid() {
    return pid;
  }


  public void setPid(String pid) {
    this.pid = pid;
  }


  public ItemData barcode(String barcode) {
    
    this.barcode = barcode;
    return this;
  }

   /**
   * The item&#39;s barcode. If not sent as part of the PUT or POST actions, Alma will generate a barcode based on the barcode generation rules.
   * @return barcode
  **/
  
  @ApiModelProperty(example = "39031031697261", value = "The item's barcode. If not sent as part of the PUT or POST actions, Alma will generate a barcode based on the barcode generation rules.")
  @JsonProperty(JSON_PROPERTY_BARCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "barcode")

  public String getBarcode() {
    return barcode;
  }


  public void setBarcode(String barcode) {
    this.barcode = barcode;
  }


  public ItemData creationDate(Date creationDate) {
    
    this.creationDate = creationDate;
    return this;
  }

   /**
   * The date the item was created. Output parameter.
   * @return creationDate
  **/
  
  @ApiModelProperty(value = "The date the item was created. Output parameter.")
  @JsonProperty(JSON_PROPERTY_CREATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "creation_date")

  public Date getCreationDate() {
    return creationDate;
  }


  public void setCreationDate(Date creationDate) {
    this.creationDate = creationDate;
  }


  public ItemData modificationDate(Date modificationDate) {
    
    this.modificationDate = modificationDate;
    return this;
  }

   /**
   * The date the item was modified. Output parameter.
   * @return modificationDate
  **/
  
  @ApiModelProperty(value = "The date the item was modified. Output parameter.")
  @JsonProperty(JSON_PROPERTY_MODIFICATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "modification_date")

  public Date getModificationDate() {
    return modificationDate;
  }


  public void setModificationDate(Date modificationDate) {
    this.modificationDate = modificationDate;
  }


  public ItemData baseStatus(ItemDataBaseStatus baseStatus) {
    
    this.baseStatus = baseStatus;
    return this;
  }

   /**
   * Get baseStatus
   * @return baseStatus
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BASE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "base_status")

  public ItemDataBaseStatus getBaseStatus() {
    return baseStatus;
  }


  public void setBaseStatus(ItemDataBaseStatus baseStatus) {
    this.baseStatus = baseStatus;
  }


  public ItemData awaitingReshelving(Boolean awaitingReshelving) {
    
    this.awaitingReshelving = awaitingReshelving;
    return this;
  }

   /**
   * Indicates whether the item is currently waiting to be reshelved, according to the library/circulation desk/reshelve without transit rule definitions.
   * @return awaitingReshelving
  **/
  
  @ApiModelProperty(example = "false", value = "Indicates whether the item is currently waiting to be reshelved, according to the library/circulation desk/reshelve without transit rule definitions.")
  @JsonProperty(JSON_PROPERTY_AWAITING_RESHELVING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "awaiting_reshelving")

  public Boolean getAwaitingReshelving() {
    return awaitingReshelving;
  }


  public void setAwaitingReshelving(Boolean awaitingReshelving) {
    this.awaitingReshelving = awaitingReshelving;
  }


  public ItemData reshelvingTime(OffsetDateTime reshelvingTime) {
    
    this.reshelvingTime = reshelvingTime;
    return this;
  }

   /**
   * Indicates the time when the item will be reshelved, according to the library/circulation desk/reshelve without transit rule definitions.
   * @return reshelvingTime
  **/
  
  @ApiModelProperty(example = "2020-06-23T14:00Z", value = "Indicates the time when the item will be reshelved, according to the library/circulation desk/reshelve without transit rule definitions.")
  @JsonProperty(JSON_PROPERTY_RESHELVING_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "reshelving_time")

  public OffsetDateTime getReshelvingTime() {
    return reshelvingTime;
  }


  public void setReshelvingTime(OffsetDateTime reshelvingTime) {
    this.reshelvingTime = reshelvingTime;
  }


  public ItemData physicalMaterialType(ItemDataPhysicalMaterialType physicalMaterialType) {
    
    this.physicalMaterialType = physicalMaterialType;
    return this;
  }

   /**
   * Get physicalMaterialType
   * @return physicalMaterialType
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PHYSICAL_MATERIAL_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "physical_material_type")

  public ItemDataPhysicalMaterialType getPhysicalMaterialType() {
    return physicalMaterialType;
  }


  public void setPhysicalMaterialType(ItemDataPhysicalMaterialType physicalMaterialType) {
    this.physicalMaterialType = physicalMaterialType;
  }


  public ItemData policy(ItemDataPolicy policy) {
    
    this.policy = policy;
    return this;
  }

   /**
   * Get policy
   * @return policy
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POLICY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "policy")

  public ItemDataPolicy getPolicy() {
    return policy;
  }


  public void setPolicy(ItemDataPolicy policy) {
    this.policy = policy;
  }


  public ItemData provenance(ItemDataProvenance provenance) {
    
    this.provenance = provenance;
    return this;
  }

   /**
   * Get provenance
   * @return provenance
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROVENANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "provenance")

  public ItemDataProvenance getProvenance() {
    return provenance;
  }


  public void setProvenance(ItemDataProvenance provenance) {
    this.provenance = provenance;
  }


  public ItemData poLine(String poLine) {
    
    this.poLine = poLine;
    return this;
  }

   /**
   * The related PO line number. In the GET action, this might be the matching holding&#39;s PO line (in case of continuous PO line). In POST and PUT actions, it is possible to update only the specific item&#39;s PO line. Hence, in case the PO line in this field is continuous, it will be ignored. Such an update should be done in the holding record itself.
   * @return poLine
  **/
  
  @ApiModelProperty(example = "08-000030003", value = "The related PO line number. In the GET action, this might be the matching holding's PO line (in case of continuous PO line). In POST and PUT actions, it is possible to update only the specific item's PO line. Hence, in case the PO line in this field is continuous, it will be ignored. Such an update should be done in the holding record itself.")
  @JsonProperty(JSON_PROPERTY_PO_LINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "po_line")

  public String getPoLine() {
    return poLine;
  }


  public void setPoLine(String poLine) {
    this.poLine = poLine;
  }


  public ItemData isMagnetic(Boolean isMagnetic) {
    
    this.isMagnetic = isMagnetic;
    return this;
  }

   /**
   * Indicates whether the item contains a magnet which can cause it to be damaged when scanned by a self-check machine. Optional. Default is False.
   * @return isMagnetic
  **/
  
  @ApiModelProperty(example = "false", value = "Indicates whether the item contains a magnet which can cause it to be damaged when scanned by a self-check machine. Optional. Default is False.")
  @JsonProperty(JSON_PROPERTY_IS_MAGNETIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "is_magnetic")

  public Boolean getIsMagnetic() {
    return isMagnetic;
  }


  public void setIsMagnetic(Boolean isMagnetic) {
    this.isMagnetic = isMagnetic;
  }


  public ItemData arrivalDate(Date arrivalDate) {
    
    this.arrivalDate = arrivalDate;
    return this;
  }

   /**
   * The date the material was actually received/activated for the first time.
   * @return arrivalDate
  **/
  
  @ApiModelProperty(value = "The date the material was actually received/activated for the first time.")
  @JsonProperty(JSON_PROPERTY_ARRIVAL_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "arrival_date")

  public Date getArrivalDate() {
    return arrivalDate;
  }


  public void setArrivalDate(Date arrivalDate) {
    this.arrivalDate = arrivalDate;
  }


  public ItemData expectedArrivalDate(Date expectedArrivalDate) {
    
    this.expectedArrivalDate = expectedArrivalDate;
    return this;
  }

   /**
   * The date the item was expected to be received.
   * @return expectedArrivalDate
  **/
  
  @ApiModelProperty(value = "The date the item was expected to be received.")
  @JsonProperty(JSON_PROPERTY_EXPECTED_ARRIVAL_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "expected_arrival_date")

  public Date getExpectedArrivalDate() {
    return expectedArrivalDate;
  }


  public void setExpectedArrivalDate(Date expectedArrivalDate) {
    this.expectedArrivalDate = expectedArrivalDate;
  }


  public ItemData yearOfIssue(String yearOfIssue) {
    
    this.yearOfIssue = yearOfIssue;
    return this;
  }

   /**
   * The related year for an issue item.
   * @return yearOfIssue
  **/
  
  @ApiModelProperty(example = "2015", value = "The related year for an issue item.")
  @JsonProperty(JSON_PROPERTY_YEAR_OF_ISSUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "year_of_issue")

  public String getYearOfIssue() {
    return yearOfIssue;
  }


  public void setYearOfIssue(String yearOfIssue) {
    this.yearOfIssue = yearOfIssue;
  }


  public ItemData enumerationA(String enumerationA) {
    
    this.enumerationA = enumerationA;
    return this;
  }

   /**
   * enumeration A
   * @return enumerationA
  **/
  
  @ApiModelProperty(value = "enumeration A")
  @JsonProperty(JSON_PROPERTY_ENUMERATION_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "enumeration_a")

  public String getEnumerationA() {
    return enumerationA;
  }


  public void setEnumerationA(String enumerationA) {
    this.enumerationA = enumerationA;
  }


  public ItemData enumerationB(String enumerationB) {
    
    this.enumerationB = enumerationB;
    return this;
  }

   /**
   * enumeration B
   * @return enumerationB
  **/
  
  @ApiModelProperty(value = "enumeration B")
  @JsonProperty(JSON_PROPERTY_ENUMERATION_B)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "enumeration_b")

  public String getEnumerationB() {
    return enumerationB;
  }


  public void setEnumerationB(String enumerationB) {
    this.enumerationB = enumerationB;
  }


  public ItemData enumerationC(String enumerationC) {
    
    this.enumerationC = enumerationC;
    return this;
  }

   /**
   * enumeration C
   * @return enumerationC
  **/
  
  @ApiModelProperty(value = "enumeration C")
  @JsonProperty(JSON_PROPERTY_ENUMERATION_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "enumeration_c")

  public String getEnumerationC() {
    return enumerationC;
  }


  public void setEnumerationC(String enumerationC) {
    this.enumerationC = enumerationC;
  }


  public ItemData enumerationD(String enumerationD) {
    
    this.enumerationD = enumerationD;
    return this;
  }

   /**
   * enumeration D
   * @return enumerationD
  **/
  
  @ApiModelProperty(value = "enumeration D")
  @JsonProperty(JSON_PROPERTY_ENUMERATION_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "enumeration_d")

  public String getEnumerationD() {
    return enumerationD;
  }


  public void setEnumerationD(String enumerationD) {
    this.enumerationD = enumerationD;
  }


  public ItemData enumerationE(String enumerationE) {
    
    this.enumerationE = enumerationE;
    return this;
  }

   /**
   * enumeration E
   * @return enumerationE
  **/
  
  @ApiModelProperty(value = "enumeration E")
  @JsonProperty(JSON_PROPERTY_ENUMERATION_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "enumeration_e")

  public String getEnumerationE() {
    return enumerationE;
  }


  public void setEnumerationE(String enumerationE) {
    this.enumerationE = enumerationE;
  }


  public ItemData enumerationF(String enumerationF) {
    
    this.enumerationF = enumerationF;
    return this;
  }

   /**
   * enumeration F
   * @return enumerationF
  **/
  
  @ApiModelProperty(value = "enumeration F")
  @JsonProperty(JSON_PROPERTY_ENUMERATION_F)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "enumeration_f")

  public String getEnumerationF() {
    return enumerationF;
  }


  public void setEnumerationF(String enumerationF) {
    this.enumerationF = enumerationF;
  }


  public ItemData enumerationG(String enumerationG) {
    
    this.enumerationG = enumerationG;
    return this;
  }

   /**
   * enumeration G
   * @return enumerationG
  **/
  
  @ApiModelProperty(value = "enumeration G")
  @JsonProperty(JSON_PROPERTY_ENUMERATION_G)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "enumeration_g")

  public String getEnumerationG() {
    return enumerationG;
  }


  public void setEnumerationG(String enumerationG) {
    this.enumerationG = enumerationG;
  }


  public ItemData enumerationH(String enumerationH) {
    
    this.enumerationH = enumerationH;
    return this;
  }

   /**
   * enumeration H
   * @return enumerationH
  **/
  
  @ApiModelProperty(value = "enumeration H")
  @JsonProperty(JSON_PROPERTY_ENUMERATION_H)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "enumeration_h")

  public String getEnumerationH() {
    return enumerationH;
  }


  public void setEnumerationH(String enumerationH) {
    this.enumerationH = enumerationH;
  }


  public ItemData chronologyI(String chronologyI) {
    
    this.chronologyI = chronologyI;
    return this;
  }

   /**
   * chronology I
   * @return chronologyI
  **/
  
  @ApiModelProperty(value = "chronology I")
  @JsonProperty(JSON_PROPERTY_CHRONOLOGY_I)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "chronology_i")

  public String getChronologyI() {
    return chronologyI;
  }


  public void setChronologyI(String chronologyI) {
    this.chronologyI = chronologyI;
  }


  public ItemData chronologyJ(String chronologyJ) {
    
    this.chronologyJ = chronologyJ;
    return this;
  }

   /**
   * chronology J
   * @return chronologyJ
  **/
  
  @ApiModelProperty(value = "chronology J")
  @JsonProperty(JSON_PROPERTY_CHRONOLOGY_J)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "chronology_j")

  public String getChronologyJ() {
    return chronologyJ;
  }


  public void setChronologyJ(String chronologyJ) {
    this.chronologyJ = chronologyJ;
  }


  public ItemData chronologyK(String chronologyK) {
    
    this.chronologyK = chronologyK;
    return this;
  }

   /**
   * chronology K
   * @return chronologyK
  **/
  
  @ApiModelProperty(value = "chronology K")
  @JsonProperty(JSON_PROPERTY_CHRONOLOGY_K)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "chronology_k")

  public String getChronologyK() {
    return chronologyK;
  }


  public void setChronologyK(String chronologyK) {
    this.chronologyK = chronologyK;
  }


  public ItemData chronologyL(String chronologyL) {
    
    this.chronologyL = chronologyL;
    return this;
  }

   /**
   * chronology L
   * @return chronologyL
  **/
  
  @ApiModelProperty(value = "chronology L")
  @JsonProperty(JSON_PROPERTY_CHRONOLOGY_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "chronology_l")

  public String getChronologyL() {
    return chronologyL;
  }


  public void setChronologyL(String chronologyL) {
    this.chronologyL = chronologyL;
  }


  public ItemData chronologyM(String chronologyM) {
    
    this.chronologyM = chronologyM;
    return this;
  }

   /**
   * chronology M
   * @return chronologyM
  **/
  
  @ApiModelProperty(value = "chronology M")
  @JsonProperty(JSON_PROPERTY_CHRONOLOGY_M)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "chronology_m")

  public String getChronologyM() {
    return chronologyM;
  }


  public void setChronologyM(String chronologyM) {
    this.chronologyM = chronologyM;
  }


  public ItemData description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * This item&#39;s description.
   * @return description
  **/
  
  @ApiModelProperty(example = "This item's description", value = "This item's description.")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "description")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public ItemData replacementCost(Float replacementCost) {
    
    this.replacementCost = replacementCost;
    return this;
  }

   /**
   * The charge administered to the patron if the item is lost.
   * @return replacementCost
  **/
  
  @ApiModelProperty(example = "50.0", value = "The charge administered to the patron if the item is lost.")
  @JsonProperty(JSON_PROPERTY_REPLACEMENT_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "replacement_cost")

  public Float getReplacementCost() {
    return replacementCost;
  }


  public void setReplacementCost(Float replacementCost) {
    this.replacementCost = replacementCost;
  }


  public ItemData receivingOperator(String receivingOperator) {
    
    this.receivingOperator = receivingOperator;
    return this;
  }

   /**
   * The Operator who received the item.
   * @return receivingOperator
  **/
  
  @ApiModelProperty(value = "The Operator who received the item.")
  @JsonProperty(JSON_PROPERTY_RECEIVING_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "receiving_operator")

  public String getReceivingOperator() {
    return receivingOperator;
  }


  public void setReceivingOperator(String receivingOperator) {
    this.receivingOperator = receivingOperator;
  }


  public ItemData processType(ItemDataProcessType processType) {
    
    this.processType = processType;
    return this;
  }

   /**
   * Get processType
   * @return processType
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROCESS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "process_type")

  public ItemDataProcessType getProcessType() {
    return processType;
  }


  public void setProcessType(ItemDataProcessType processType) {
    this.processType = processType;
  }


  public ItemData workOrderType(ItemDataWorkOrderType workOrderType) {
    
    this.workOrderType = workOrderType;
    return this;
  }

   /**
   * Get workOrderType
   * @return workOrderType
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WORK_ORDER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "work_order_type")

  public ItemDataWorkOrderType getWorkOrderType() {
    return workOrderType;
  }


  public void setWorkOrderType(ItemDataWorkOrderType workOrderType) {
    this.workOrderType = workOrderType;
  }


  public ItemData workOrderAt(ItemDataWorkOrderAt workOrderAt) {
    
    this.workOrderAt = workOrderAt;
    return this;
  }

   /**
   * Get workOrderAt
   * @return workOrderAt
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WORK_ORDER_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "work_order_at")

  public ItemDataWorkOrderAt getWorkOrderAt() {
    return workOrderAt;
  }


  public void setWorkOrderAt(ItemDataWorkOrderAt workOrderAt) {
    this.workOrderAt = workOrderAt;
  }


  public ItemData inventoryNumber(String inventoryNumber) {
    
    this.inventoryNumber = inventoryNumber;
    return this;
  }

   /**
   * The number of this physical item.
   * @return inventoryNumber
  **/
  
  @ApiModelProperty(example = "10791310001021", value = "The number of this physical item.")
  @JsonProperty(JSON_PROPERTY_INVENTORY_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "inventory_number")

  public String getInventoryNumber() {
    return inventoryNumber;
  }


  public void setInventoryNumber(String inventoryNumber) {
    this.inventoryNumber = inventoryNumber;
  }


  public ItemData inventoryDate(Date inventoryDate) {
    
    this.inventoryDate = inventoryDate;
    return this;
  }

   /**
   * The date the item was modified.
   * @return inventoryDate
  **/
  
  @ApiModelProperty(value = "The date the item was modified.")
  @JsonProperty(JSON_PROPERTY_INVENTORY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "inventory_date")

  public Date getInventoryDate() {
    return inventoryDate;
  }


  public void setInventoryDate(Date inventoryDate) {
    this.inventoryDate = inventoryDate;
  }


  public ItemData inventoryPrice(String inventoryPrice) {
    
    this.inventoryPrice = inventoryPrice;
    return this;
  }

   /**
   * The price of the item. The value is assumed to be in the default currency for your institution.
   * @return inventoryPrice
  **/
  
  @ApiModelProperty(example = "100", value = "The price of the item. The value is assumed to be in the default currency for your institution.")
  @JsonProperty(JSON_PROPERTY_INVENTORY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "inventory_price")

  public String getInventoryPrice() {
    return inventoryPrice;
  }


  public void setInventoryPrice(String inventoryPrice) {
    this.inventoryPrice = inventoryPrice;
  }


  public ItemData receiveNumber(String receiveNumber) {
    
    this.receiveNumber = receiveNumber;
    return this;
  }

   /**
   * The number of this physical item receive.
   * @return receiveNumber
  **/
  
  @ApiModelProperty(example = "10791310001021", value = "The number of this physical item receive.")
  @JsonProperty(JSON_PROPERTY_RECEIVE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "receive_number")

  public String getReceiveNumber() {
    return receiveNumber;
  }


  public void setReceiveNumber(String receiveNumber) {
    this.receiveNumber = receiveNumber;
  }


  public ItemData weedingNumber(String weedingNumber) {
    
    this.weedingNumber = weedingNumber;
    return this;
  }

   /**
   * The number of this physical item weeding.
   * @return weedingNumber
  **/
  
  @ApiModelProperty(example = "10791310001021", value = "The number of this physical item weeding.")
  @JsonProperty(JSON_PROPERTY_WEEDING_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "weeding_number")

  public String getWeedingNumber() {
    return weedingNumber;
  }


  public void setWeedingNumber(String weedingNumber) {
    this.weedingNumber = weedingNumber;
  }


  public ItemData weedingDate(Date weedingDate) {
    
    this.weedingDate = weedingDate;
    return this;
  }

   /**
   * The date the item was weeded.
   * @return weedingDate
  **/
  
  @ApiModelProperty(value = "The date the item was weeded.")
  @JsonProperty(JSON_PROPERTY_WEEDING_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "weeding_date")

  public Date getWeedingDate() {
    return weedingDate;
  }


  public void setWeedingDate(Date weedingDate) {
    this.weedingDate = weedingDate;
  }


  public ItemData library(ItemDataLibrary library) {
    
    this.library = library;
    return this;
  }

   /**
   * Get library
   * @return library
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LIBRARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "library")

  public ItemDataLibrary getLibrary() {
    return library;
  }


  public void setLibrary(ItemDataLibrary library) {
    this.library = library;
  }


  public ItemData location(ItemDataLocation location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "location")

  public ItemDataLocation getLocation() {
    return location;
  }


  public void setLocation(ItemDataLocation location) {
    this.location = location;
  }


  public ItemData alternativeCallNumber(String alternativeCallNumber) {
    
    this.alternativeCallNumber = alternativeCallNumber;
    return this;
  }

   /**
   * The ID number for the item that corresponds to the alternative call number type.
   * @return alternativeCallNumber
  **/
  
  @ApiModelProperty(example = "121108431000", value = "The ID number for the item that corresponds to the alternative call number type.")
  @JsonProperty(JSON_PROPERTY_ALTERNATIVE_CALL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "alternative_call_number")

  public String getAlternativeCallNumber() {
    return alternativeCallNumber;
  }


  public void setAlternativeCallNumber(String alternativeCallNumber) {
    this.alternativeCallNumber = alternativeCallNumber;
  }


  public ItemData alternativeCallNumberType(ItemDataAlternativeCallNumberType alternativeCallNumberType) {
    
    this.alternativeCallNumberType = alternativeCallNumberType;
    return this;
  }

   /**
   * Get alternativeCallNumberType
   * @return alternativeCallNumberType
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ALTERNATIVE_CALL_NUMBER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "alternative_call_number_type")

  public ItemDataAlternativeCallNumberType getAlternativeCallNumberType() {
    return alternativeCallNumberType;
  }


  public void setAlternativeCallNumberType(ItemDataAlternativeCallNumberType alternativeCallNumberType) {
    this.alternativeCallNumberType = alternativeCallNumberType;
  }


  public ItemData altNumberSource(String altNumberSource) {
    
    this.altNumberSource = altNumberSource;
    return this;
  }

   /**
   * The ID number for the item that corresponds to the alternative call number type.
   * @return altNumberSource
  **/
  
  @ApiModelProperty(example = "105510551055", value = "The ID number for the item that corresponds to the alternative call number type.")
  @JsonProperty(JSON_PROPERTY_ALT_NUMBER_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "alt_number_source")

  public String getAltNumberSource() {
    return altNumberSource;
  }


  public void setAltNumberSource(String altNumberSource) {
    this.altNumberSource = altNumberSource;
  }


  public ItemData storageLocationId(String storageLocationId) {
    
    this.storageLocationId = storageLocationId;
    return this;
  }

   /**
   * The ID number of the location where the item is stored.
   * @return storageLocationId
  **/
  
  @ApiModelProperty(example = "1021021021", value = "The ID number of the location where the item is stored.")
  @JsonProperty(JSON_PROPERTY_STORAGE_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "storage_location_id")

  public String getStorageLocationId() {
    return storageLocationId;
  }


  public void setStorageLocationId(String storageLocationId) {
    this.storageLocationId = storageLocationId;
  }


  public ItemData pages(String pages) {
    
    this.pages = pages;
    return this;
  }

   /**
   * The item&#39;s number of pages.
   * @return pages
  **/
  
  @ApiModelProperty(example = "100", value = "The item's number of pages.")
  @JsonProperty(JSON_PROPERTY_PAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "pages")

  public String getPages() {
    return pages;
  }


  public void setPages(String pages) {
    this.pages = pages;
  }


  public ItemData pieces(String pieces) {
    
    this.pieces = pieces;
    return this;
  }

   /**
   * The item&#39;s number of pieces.
   * @return pieces
  **/
  
  @ApiModelProperty(example = "100", value = "The item's number of pieces.")
  @JsonProperty(JSON_PROPERTY_PIECES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "pieces")

  public String getPieces() {
    return pieces;
  }


  public void setPieces(String pieces) {
    this.pieces = pieces;
  }


  public ItemData publicNote(String publicNote) {
    
    this.publicNote = publicNote;
    return this;
  }

   /**
   * Contains note content that is displayed in Primo.
   * @return publicNote
  **/
  
  @ApiModelProperty(example = "Public note", value = "Contains note content that is displayed in Primo.")
  @JsonProperty(JSON_PROPERTY_PUBLIC_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "public_note")

  public String getPublicNote() {
    return publicNote;
  }


  public void setPublicNote(String publicNote) {
    this.publicNote = publicNote;
  }


  public ItemData fulfillmentNote(String fulfillmentNote) {
    
    this.fulfillmentNote = fulfillmentNote;
    return this;
  }

   /**
   * Contains note content that is displayed during the circulation process.
   * @return fulfillmentNote
  **/
  
  @ApiModelProperty(example = "Fulfillment note", value = "Contains note content that is displayed during the circulation process.")
  @JsonProperty(JSON_PROPERTY_FULFILLMENT_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "fulfillment_note")

  public String getFulfillmentNote() {
    return fulfillmentNote;
  }


  public void setFulfillmentNote(String fulfillmentNote) {
    this.fulfillmentNote = fulfillmentNote;
  }


  public ItemData dueDate(OffsetDateTime dueDate) {
    
    this.dueDate = dueDate;
    return this;
  }

   /**
   * The item&#39;s due date. If not on loan - empty. This field will be populated only if the &#39;expand&#39; query parameter is sent.
   * @return dueDate
  **/
  
  @ApiModelProperty(example = "2020-06-23T14:00Z", value = "The item's due date. If not on loan - empty. This field will be populated only if the 'expand' query parameter is sent.")
  @JsonProperty(JSON_PROPERTY_DUE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "due_date")

  public OffsetDateTime getDueDate() {
    return dueDate;
  }


  public void setDueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
  }


  public ItemData dueDatePolicy(String dueDatePolicy) {
    
    this.dueDatePolicy = dueDatePolicy;
    return this;
  }

   /**
   * The loan policy as displayed in discovery. This field will be populated only if the &#39;expand&#39; query parameter is sent.
   * @return dueDatePolicy
  **/
  
  @ApiModelProperty(value = "The loan policy as displayed in discovery. This field will be populated only if the 'expand' query parameter is sent.")
  @JsonProperty(JSON_PROPERTY_DUE_DATE_POLICY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "due_date_policy")

  public String getDueDatePolicy() {
    return dueDatePolicy;
  }


  public void setDueDatePolicy(String dueDatePolicy) {
    this.dueDatePolicy = dueDatePolicy;
  }


  public ItemData internalNote1(String internalNote1) {
    
    this.internalNote1 = internalNote1;
    return this;
  }

   /**
   * Contains note content regarding an item for internal use by Alma staff.
   * @return internalNote1
  **/
  
  @ApiModelProperty(value = "Contains note content regarding an item for internal use by Alma staff.")
  @JsonProperty(JSON_PROPERTY_INTERNAL_NOTE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "internal_note_1")

  public String getInternalNote1() {
    return internalNote1;
  }


  public void setInternalNote1(String internalNote1) {
    this.internalNote1 = internalNote1;
  }


  public ItemData internalNote2(String internalNote2) {
    
    this.internalNote2 = internalNote2;
    return this;
  }

   /**
   * Contains note content regarding an item for internal use by Alma staff.
   * @return internalNote2
  **/
  
  @ApiModelProperty(value = "Contains note content regarding an item for internal use by Alma staff.")
  @JsonProperty(JSON_PROPERTY_INTERNAL_NOTE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "internal_note_2")

  public String getInternalNote2() {
    return internalNote2;
  }


  public void setInternalNote2(String internalNote2) {
    this.internalNote2 = internalNote2;
  }


  public ItemData internalNote3(String internalNote3) {
    
    this.internalNote3 = internalNote3;
    return this;
  }

   /**
   * Contains note content regarding an item for internal use by Alma staff.
   * @return internalNote3
  **/
  
  @ApiModelProperty(value = "Contains note content regarding an item for internal use by Alma staff.")
  @JsonProperty(JSON_PROPERTY_INTERNAL_NOTE3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "internal_note_3")

  public String getInternalNote3() {
    return internalNote3;
  }


  public void setInternalNote3(String internalNote3) {
    this.internalNote3 = internalNote3;
  }


  public ItemData statisticsNote1(String statisticsNote1) {
    
    this.statisticsNote1 = statisticsNote1;
    return this;
  }

   /**
   * Contains note content that is exposed in analytics.
   * @return statisticsNote1
  **/
  
  @ApiModelProperty(value = "Contains note content that is exposed in analytics.")
  @JsonProperty(JSON_PROPERTY_STATISTICS_NOTE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "statistics_note_1")

  public String getStatisticsNote1() {
    return statisticsNote1;
  }


  public void setStatisticsNote1(String statisticsNote1) {
    this.statisticsNote1 = statisticsNote1;
  }


  public ItemData statisticsNote2(String statisticsNote2) {
    
    this.statisticsNote2 = statisticsNote2;
    return this;
  }

   /**
   * Contains note content that is exposed in analytics.
   * @return statisticsNote2
  **/
  
  @ApiModelProperty(value = "Contains note content that is exposed in analytics.")
  @JsonProperty(JSON_PROPERTY_STATISTICS_NOTE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "statistics_note_2")

  public String getStatisticsNote2() {
    return statisticsNote2;
  }


  public void setStatisticsNote2(String statisticsNote2) {
    this.statisticsNote2 = statisticsNote2;
  }


  public ItemData statisticsNote3(String statisticsNote3) {
    
    this.statisticsNote3 = statisticsNote3;
    return this;
  }

   /**
   * Contains note content that is exposed in analytics.
   * @return statisticsNote3
  **/
  
  @ApiModelProperty(value = "Contains note content that is exposed in analytics.")
  @JsonProperty(JSON_PROPERTY_STATISTICS_NOTE3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "statistics_note_3")

  public String getStatisticsNote3() {
    return statisticsNote3;
  }


  public void setStatisticsNote3(String statisticsNote3) {
    this.statisticsNote3 = statisticsNote3;
  }


  public ItemData requested(Boolean requested) {
    
    this.requested = requested;
    return this;
  }

   /**
   * Indication whether item is requested or not. Output parameter.
   * @return requested
  **/
  
  @ApiModelProperty(example = "false", value = "Indication whether item is requested or not. Output parameter.")
  @JsonProperty(JSON_PROPERTY_REQUESTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "requested")

  public Boolean getRequested() {
    return requested;
  }


  public void setRequested(Boolean requested) {
    this.requested = requested;
  }


  public ItemData edition(String edition) {
    
    this.edition = edition;
    return this;
  }

   /**
   * Edition of the item. Output parameter. Returned only when view&#x3D;label.
   * @return edition
  **/
  
  @ApiModelProperty(value = "Edition of the item. Output parameter. Returned only when view=label.")
  @JsonProperty(JSON_PROPERTY_EDITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "edition")

  public String getEdition() {
    return edition;
  }


  public void setEdition(String edition) {
    this.edition = edition;
  }


  public ItemData imprint(String imprint) {
    
    this.imprint = imprint;
    return this;
  }

   /**
   * Imprint of the item. Output parameter. Returned only when view&#x3D;label.
   * @return imprint
  **/
  
  @ApiModelProperty(value = "Imprint of the item. Output parameter. Returned only when view=label.")
  @JsonProperty(JSON_PROPERTY_IMPRINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "imprint")

  public String getImprint() {
    return imprint;
  }


  public void setImprint(String imprint) {
    this.imprint = imprint;
  }


  public ItemData language(String language) {
    
    this.language = language;
    return this;
  }

   /**
   * Language of the item. Output parameter. Returned only when view&#x3D;label.
   * @return language
  **/
  
  @ApiModelProperty(example = "EN", value = "Language of the item. Output parameter. Returned only when view=label.")
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "language")

  public String getLanguage() {
    return language;
  }


  public void setLanguage(String language) {
    this.language = language;
  }


  public ItemData libraryDetails(LibraryDetails libraryDetails) {
    
    this.libraryDetails = libraryDetails;
    return this;
  }

   /**
   * Get libraryDetails
   * @return libraryDetails
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LIBRARY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "library_details")

  public LibraryDetails getLibraryDetails() {
    return libraryDetails;
  }


  public void setLibraryDetails(LibraryDetails libraryDetails) {
    this.libraryDetails = libraryDetails;
  }


  public ItemData altCallNo(List<String> altCallNo) {
    
    this.altCallNo = altCallNo;
    return this;
  }

  public ItemData addAltCallNoItem(String altCallNoItem) {
    if (this.altCallNo == null) {
      this.altCallNo = new ArrayList<String>();
    }
    this.altCallNo.add(altCallNoItem);
    return this;
  }

   /**
   * Get altCallNo
   * @return altCallNo
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ALT_CALL_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=alt_call_no
  @JacksonXmlElementWrapper(useWrapping = true, localName = "alt_call_no")

  public List<String> getAltCallNo() {
    return altCallNo;
  }


  public void setAltCallNo(List<String> altCallNo) {
    this.altCallNo = altCallNo;
  }


  public ItemData callNo(List<String> callNo) {
    
    this.callNo = callNo;
    return this;
  }

  public ItemData addCallNoItem(String callNoItem) {
    if (this.callNo == null) {
      this.callNo = new ArrayList<String>();
    }
    this.callNo.add(callNoItem);
    return this;
  }

   /**
   * Get callNo
   * @return callNo
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CALL_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=call_no
  @JacksonXmlElementWrapper(useWrapping = true, localName = "call_no")

  public List<String> getCallNo() {
    return callNo;
  }


  public void setCallNo(List<String> callNo) {
    this.callNo = callNo;
  }


  public ItemData issueLevelDescription(List<String> issueLevelDescription) {
    
    this.issueLevelDescription = issueLevelDescription;
    return this;
  }

  public ItemData addIssueLevelDescriptionItem(String issueLevelDescriptionItem) {
    if (this.issueLevelDescription == null) {
      this.issueLevelDescription = new ArrayList<String>();
    }
    this.issueLevelDescription.add(issueLevelDescriptionItem);
    return this;
  }

   /**
   * Get issueLevelDescription
   * @return issueLevelDescription
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISSUE_LEVEL_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=issue_level_description
  @JacksonXmlElementWrapper(useWrapping = true, localName = "issue_level_description")

  public List<String> getIssueLevelDescription() {
    return issueLevelDescription;
  }


  public void setIssueLevelDescription(List<String> issueLevelDescription) {
    this.issueLevelDescription = issueLevelDescription;
  }


  public ItemData titleAbcnph(String titleAbcnph) {
    
    this.titleAbcnph = titleAbcnph;
    return this;
  }

   /**
   * Output parameter. Returned only when view&#x3D;label.
   * @return titleAbcnph
  **/
  
  @ApiModelProperty(example = "abcnph title", value = "Output parameter. Returned only when view=label.")
  @JsonProperty(JSON_PROPERTY_TITLE_ABCNPH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "title_abcnph")

  public String getTitleAbcnph() {
    return titleAbcnph;
  }


  public void setTitleAbcnph(String titleAbcnph) {
    this.titleAbcnph = titleAbcnph;
  }


  public ItemData physicalCondition(ItemDataPhysicalCondition physicalCondition) {
    
    this.physicalCondition = physicalCondition;
    return this;
  }

   /**
   * Get physicalCondition
   * @return physicalCondition
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PHYSICAL_CONDITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "physical_condition")

  public ItemDataPhysicalCondition getPhysicalCondition() {
    return physicalCondition;
  }


  public void setPhysicalCondition(ItemDataPhysicalCondition physicalCondition) {
    this.physicalCondition = physicalCondition;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemData itemData = (ItemData) o;
    return Objects.equals(this.pid, itemData.pid) &&
        Objects.equals(this.barcode, itemData.barcode) &&
        Objects.equals(this.creationDate, itemData.creationDate) &&
        Objects.equals(this.modificationDate, itemData.modificationDate) &&
        Objects.equals(this.baseStatus, itemData.baseStatus) &&
        Objects.equals(this.awaitingReshelving, itemData.awaitingReshelving) &&
        Objects.equals(this.reshelvingTime, itemData.reshelvingTime) &&
        Objects.equals(this.physicalMaterialType, itemData.physicalMaterialType) &&
        Objects.equals(this.policy, itemData.policy) &&
        Objects.equals(this.provenance, itemData.provenance) &&
        Objects.equals(this.poLine, itemData.poLine) &&
        Objects.equals(this.isMagnetic, itemData.isMagnetic) &&
        Objects.equals(this.arrivalDate, itemData.arrivalDate) &&
        Objects.equals(this.expectedArrivalDate, itemData.expectedArrivalDate) &&
        Objects.equals(this.yearOfIssue, itemData.yearOfIssue) &&
        Objects.equals(this.enumerationA, itemData.enumerationA) &&
        Objects.equals(this.enumerationB, itemData.enumerationB) &&
        Objects.equals(this.enumerationC, itemData.enumerationC) &&
        Objects.equals(this.enumerationD, itemData.enumerationD) &&
        Objects.equals(this.enumerationE, itemData.enumerationE) &&
        Objects.equals(this.enumerationF, itemData.enumerationF) &&
        Objects.equals(this.enumerationG, itemData.enumerationG) &&
        Objects.equals(this.enumerationH, itemData.enumerationH) &&
        Objects.equals(this.chronologyI, itemData.chronologyI) &&
        Objects.equals(this.chronologyJ, itemData.chronologyJ) &&
        Objects.equals(this.chronologyK, itemData.chronologyK) &&
        Objects.equals(this.chronologyL, itemData.chronologyL) &&
        Objects.equals(this.chronologyM, itemData.chronologyM) &&
        Objects.equals(this.description, itemData.description) &&
        Objects.equals(this.replacementCost, itemData.replacementCost) &&
        Objects.equals(this.receivingOperator, itemData.receivingOperator) &&
        Objects.equals(this.processType, itemData.processType) &&
        Objects.equals(this.workOrderType, itemData.workOrderType) &&
        Objects.equals(this.workOrderAt, itemData.workOrderAt) &&
        Objects.equals(this.inventoryNumber, itemData.inventoryNumber) &&
        Objects.equals(this.inventoryDate, itemData.inventoryDate) &&
        Objects.equals(this.inventoryPrice, itemData.inventoryPrice) &&
        Objects.equals(this.receiveNumber, itemData.receiveNumber) &&
        Objects.equals(this.weedingNumber, itemData.weedingNumber) &&
        Objects.equals(this.weedingDate, itemData.weedingDate) &&
        Objects.equals(this.library, itemData.library) &&
        Objects.equals(this.location, itemData.location) &&
        Objects.equals(this.alternativeCallNumber, itemData.alternativeCallNumber) &&
        Objects.equals(this.alternativeCallNumberType, itemData.alternativeCallNumberType) &&
        Objects.equals(this.altNumberSource, itemData.altNumberSource) &&
        Objects.equals(this.storageLocationId, itemData.storageLocationId) &&
        Objects.equals(this.pages, itemData.pages) &&
        Objects.equals(this.pieces, itemData.pieces) &&
        Objects.equals(this.publicNote, itemData.publicNote) &&
        Objects.equals(this.fulfillmentNote, itemData.fulfillmentNote) &&
        Objects.equals(this.dueDate, itemData.dueDate) &&
        Objects.equals(this.dueDatePolicy, itemData.dueDatePolicy) &&
        Objects.equals(this.internalNote1, itemData.internalNote1) &&
        Objects.equals(this.internalNote2, itemData.internalNote2) &&
        Objects.equals(this.internalNote3, itemData.internalNote3) &&
        Objects.equals(this.statisticsNote1, itemData.statisticsNote1) &&
        Objects.equals(this.statisticsNote2, itemData.statisticsNote2) &&
        Objects.equals(this.statisticsNote3, itemData.statisticsNote3) &&
        Objects.equals(this.requested, itemData.requested) &&
        Objects.equals(this.edition, itemData.edition) &&
        Objects.equals(this.imprint, itemData.imprint) &&
        Objects.equals(this.language, itemData.language) &&
        Objects.equals(this.libraryDetails, itemData.libraryDetails) &&
        Objects.equals(this.altCallNo, itemData.altCallNo) &&
        Objects.equals(this.callNo, itemData.callNo) &&
        Objects.equals(this.issueLevelDescription, itemData.issueLevelDescription) &&
        Objects.equals(this.titleAbcnph, itemData.titleAbcnph) &&
        Objects.equals(this.physicalCondition, itemData.physicalCondition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pid, barcode, creationDate, modificationDate, baseStatus, awaitingReshelving, reshelvingTime, physicalMaterialType, policy, provenance, poLine, isMagnetic, arrivalDate, expectedArrivalDate, yearOfIssue, enumerationA, enumerationB, enumerationC, enumerationD, enumerationE, enumerationF, enumerationG, enumerationH, chronologyI, chronologyJ, chronologyK, chronologyL, chronologyM, description, replacementCost, receivingOperator, processType, workOrderType, workOrderAt, inventoryNumber, inventoryDate, inventoryPrice, receiveNumber, weedingNumber, weedingDate, library, location, alternativeCallNumber, alternativeCallNumberType, altNumberSource, storageLocationId, pages, pieces, publicNote, fulfillmentNote, dueDate, dueDatePolicy, internalNote1, internalNote2, internalNote3, statisticsNote1, statisticsNote2, statisticsNote3, requested, edition, imprint, language, libraryDetails, altCallNo, callNo, issueLevelDescription, titleAbcnph, physicalCondition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemData2 {\n");
    sb.append("    pid: ").append(toIndentedString(pid)).append("\n");
    sb.append("    barcode: ").append(toIndentedString(barcode)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    modificationDate: ").append(toIndentedString(modificationDate)).append("\n");
    sb.append("    baseStatus: ").append(toIndentedString(baseStatus)).append("\n");
    sb.append("    awaitingReshelving: ").append(toIndentedString(awaitingReshelving)).append("\n");
    sb.append("    reshelvingTime: ").append(toIndentedString(reshelvingTime)).append("\n");
    sb.append("    physicalMaterialType: ").append(toIndentedString(physicalMaterialType)).append("\n");
    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");
    sb.append("    provenance: ").append(toIndentedString(provenance)).append("\n");
    sb.append("    poLine: ").append(toIndentedString(poLine)).append("\n");
    sb.append("    isMagnetic: ").append(toIndentedString(isMagnetic)).append("\n");
    sb.append("    arrivalDate: ").append(toIndentedString(arrivalDate)).append("\n");
    sb.append("    expectedArrivalDate: ").append(toIndentedString(expectedArrivalDate)).append("\n");
    sb.append("    yearOfIssue: ").append(toIndentedString(yearOfIssue)).append("\n");
    sb.append("    enumerationA: ").append(toIndentedString(enumerationA)).append("\n");
    sb.append("    enumerationB: ").append(toIndentedString(enumerationB)).append("\n");
    sb.append("    enumerationC: ").append(toIndentedString(enumerationC)).append("\n");
    sb.append("    enumerationD: ").append(toIndentedString(enumerationD)).append("\n");
    sb.append("    enumerationE: ").append(toIndentedString(enumerationE)).append("\n");
    sb.append("    enumerationF: ").append(toIndentedString(enumerationF)).append("\n");
    sb.append("    enumerationG: ").append(toIndentedString(enumerationG)).append("\n");
    sb.append("    enumerationH: ").append(toIndentedString(enumerationH)).append("\n");
    sb.append("    chronologyI: ").append(toIndentedString(chronologyI)).append("\n");
    sb.append("    chronologyJ: ").append(toIndentedString(chronologyJ)).append("\n");
    sb.append("    chronologyK: ").append(toIndentedString(chronologyK)).append("\n");
    sb.append("    chronologyL: ").append(toIndentedString(chronologyL)).append("\n");
    sb.append("    chronologyM: ").append(toIndentedString(chronologyM)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    replacementCost: ").append(toIndentedString(replacementCost)).append("\n");
    sb.append("    receivingOperator: ").append(toIndentedString(receivingOperator)).append("\n");
    sb.append("    processType: ").append(toIndentedString(processType)).append("\n");
    sb.append("    workOrderType: ").append(toIndentedString(workOrderType)).append("\n");
    sb.append("    workOrderAt: ").append(toIndentedString(workOrderAt)).append("\n");
    sb.append("    inventoryNumber: ").append(toIndentedString(inventoryNumber)).append("\n");
    sb.append("    inventoryDate: ").append(toIndentedString(inventoryDate)).append("\n");
    sb.append("    inventoryPrice: ").append(toIndentedString(inventoryPrice)).append("\n");
    sb.append("    receiveNumber: ").append(toIndentedString(receiveNumber)).append("\n");
    sb.append("    weedingNumber: ").append(toIndentedString(weedingNumber)).append("\n");
    sb.append("    weedingDate: ").append(toIndentedString(weedingDate)).append("\n");
    sb.append("    library: ").append(toIndentedString(library)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    alternativeCallNumber: ").append(toIndentedString(alternativeCallNumber)).append("\n");
    sb.append("    alternativeCallNumberType: ").append(toIndentedString(alternativeCallNumberType)).append("\n");
    sb.append("    altNumberSource: ").append(toIndentedString(altNumberSource)).append("\n");
    sb.append("    storageLocationId: ").append(toIndentedString(storageLocationId)).append("\n");
    sb.append("    pages: ").append(toIndentedString(pages)).append("\n");
    sb.append("    pieces: ").append(toIndentedString(pieces)).append("\n");
    sb.append("    publicNote: ").append(toIndentedString(publicNote)).append("\n");
    sb.append("    fulfillmentNote: ").append(toIndentedString(fulfillmentNote)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    dueDatePolicy: ").append(toIndentedString(dueDatePolicy)).append("\n");
    sb.append("    internalNote1: ").append(toIndentedString(internalNote1)).append("\n");
    sb.append("    internalNote2: ").append(toIndentedString(internalNote2)).append("\n");
    sb.append("    internalNote3: ").append(toIndentedString(internalNote3)).append("\n");
    sb.append("    statisticsNote1: ").append(toIndentedString(statisticsNote1)).append("\n");
    sb.append("    statisticsNote2: ").append(toIndentedString(statisticsNote2)).append("\n");
    sb.append("    statisticsNote3: ").append(toIndentedString(statisticsNote3)).append("\n");
    sb.append("    requested: ").append(toIndentedString(requested)).append("\n");
    sb.append("    edition: ").append(toIndentedString(edition)).append("\n");
    sb.append("    imprint: ").append(toIndentedString(imprint)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    libraryDetails: ").append(toIndentedString(libraryDetails)).append("\n");
    sb.append("    altCallNo: ").append(toIndentedString(altCallNo)).append("\n");
    sb.append("    callNo: ").append(toIndentedString(callNo)).append("\n");
    sb.append("    issueLevelDescription: ").append(toIndentedString(issueLevelDescription)).append("\n");
    sb.append("    titleAbcnph: ").append(toIndentedString(titleAbcnph)).append("\n");
    sb.append("    physicalCondition: ").append(toIndentedString(physicalCondition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

