/*
 * Ex Libris APIs
 * For more information on how to use these APIs, including how to create an API key required for authentication, see [Alma REST APIs](https://developers.exlibrisgroup.com/alma/apis).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.unidue.ub.alma.shared.acq;

import java.util.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.*;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

import java.io.Serializable;

import com.fasterxml.jackson.dataformat.xml.annotation.*;
import javax.xml.bind.annotation.*;

/**
 * PO line Object.
 */
@ApiModel(description = "PO line Object.")
@JsonPropertyOrder({
  PoLine.JSON_PROPERTY_LINK,
  PoLine.JSON_PROPERTY_NUMBER,
  PoLine.JSON_PROPERTY_STATUS,
  PoLine.JSON_PROPERTY_OWNER,
  PoLine.JSON_PROPERTY_TYPE,
  PoLine.JSON_PROPERTY_VENDOR,
  PoLine.JSON_PROPERTY_VENDOR_ACCOUNT,
  PoLine.JSON_PROPERTY_RECLAIM_INTERVAL,
  PoLine.JSON_PROPERTY_EXPECTED_RECEIPT_INTERVAL,
  PoLine.JSON_PROPERTY_CLAIMING_INTERVAL,
  PoLine.JSON_PROPERTY_EXPECTED_ACTIVATION_INTERVAL,
  PoLine.JSON_PROPERTY_SUBSCRIPTION_INTERVAL,
  PoLine.JSON_PROPERTY_EXPECTED_ACTIVATION_DATE,
  PoLine.JSON_PROPERTY_E_ACTIVATION_DUE_INTERVAL,
  PoLine.JSON_PROPERTY_ACQUISITION_METHOD,
  PoLine.JSON_PROPERTY_NO_CHARGE,
  PoLine.JSON_PROPERTY_RUSH,
  PoLine.JSON_PROPERTY_CANCELLATION_RESTRICTION,
  PoLine.JSON_PROPERTY_CANCELLATION_RESTRICTION_NOTE,
  PoLine.JSON_PROPERTY_PRICE,
  PoLine.JSON_PROPERTY_DISCOUNT,
  PoLine.JSON_PROPERTY_VENDOR_REFERENCE_NUMBER,
  PoLine.JSON_PROPERTY_VENDOR_REFERENCE_NUMBER_TYPE,
  PoLine.JSON_PROPERTY_SOURCE_TYPE,
  PoLine.JSON_PROPERTY_PO_NUMBER,
  PoLine.JSON_PROPERTY_INVOICE_REFERENCE,
  PoLine.JSON_PROPERTY_RESOURCE_METADATA,
  PoLine.JSON_PROPERTY_FUND_DISTRIBUTION,
  PoLine.JSON_PROPERTY_REPORTING_CODE,
  PoLine.JSON_PROPERTY_SECONDARY_REPORTING_CODE,
  PoLine.JSON_PROPERTY_TERTIARY_REPORTING_CODE,
  PoLine.JSON_PROPERTY_VENDOR_NOTE,
  PoLine.JSON_PROPERTY_RECEIVING_NOTE,
  PoLine.JSON_PROPERTY_ALERT,
  PoLine.JSON_PROPERTY_NOTE,
  PoLine.JSON_PROPERTY_LOCATION,
  PoLine.JSON_PROPERTY_INTERESTED_USER,
  PoLine.JSON_PROPERTY_LICENSE,
  PoLine.JSON_PROPERTY_ACCESS_MODEL,
  PoLine.JSON_PROPERTY_URL,
  PoLine.JSON_PROPERTY_BASE_STATUS,
  PoLine.JSON_PROPERTY_ACCESS_PROVIDER,
  PoLine.JSON_PROPERTY_MANUAL_RENEWAL,
  PoLine.JSON_PROPERTY_RENEWAL_CYCLE,
  PoLine.JSON_PROPERTY_SUBSCRIPTION_FROM_DATE,
  PoLine.JSON_PROPERTY_SUBSCRIPTION_TO_DATE,
  PoLine.JSON_PROPERTY_RENEWAL_DATE,
  PoLine.JSON_PROPERTY_RENEWAL_PERIOD,
  PoLine.JSON_PROPERTY_MATERIAL_TYPE,
  PoLine.JSON_PROPERTY_CREATED_DATE,
  PoLine.JSON_PROPERTY_STATUS_DATE,
  PoLine.JSON_PROPERTY_EXPECTED_RECEIPT_DATE
})

@XmlRootElement(name = "po_line")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "po_line")
public class PoLine implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_LINK = "link";
  @XmlAttribute(name = "link")
  private String link;

  public static final String JSON_PROPERTY_NUMBER = "number";
  @XmlElement(name = "number")
  private String number;

  public static final String JSON_PROPERTY_STATUS = "status";
  @XmlElement(name = "status")
  private PoLineStatus status;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @XmlElement(name = "owner")
  private PoLineOwner owner;

  public static final String JSON_PROPERTY_TYPE = "type";
  @XmlElement(name = "type")
  private PoLineType type;

  public static final String JSON_PROPERTY_VENDOR = "vendor";
  @XmlElement(name = "vendor")
  private PoLineVendor vendor;

  public static final String JSON_PROPERTY_VENDOR_ACCOUNT = "vendor_account";
  @XmlElement(name = "vendor_account")
  private String vendorAccount;

  public static final String JSON_PROPERTY_RECLAIM_INTERVAL = "reclaim_interval";
  @XmlElement(name = "reclaim_interval")
  private String reclaimInterval;

  public static final String JSON_PROPERTY_EXPECTED_RECEIPT_INTERVAL = "expected_receipt_interval";
  @XmlElement(name = "expected_receipt_interval")
  private String expectedReceiptInterval;

  public static final String JSON_PROPERTY_CLAIMING_INTERVAL = "claiming_interval";
  @XmlElement(name = "claiming_interval")
  private String claimingInterval;

  public static final String JSON_PROPERTY_EXPECTED_ACTIVATION_INTERVAL = "expected_activation_interval";
  @XmlElement(name = "expected_activation_interval")
  private String expectedActivationInterval;

  public static final String JSON_PROPERTY_SUBSCRIPTION_INTERVAL = "subscription_interval";
  @XmlElement(name = "subscription_interval")
  private String subscriptionInterval;

  public static final String JSON_PROPERTY_EXPECTED_ACTIVATION_DATE = "expected_activation_date";
  @XmlElement(name = "expected_activation_date")
  private Date expectedActivationDate;

  public static final String JSON_PROPERTY_E_ACTIVATION_DUE_INTERVAL = "e_activation_due_interval";
  @XmlElement(name = "e_activation_due_interval")
  private String eActivationDueInterval;

  public static final String JSON_PROPERTY_ACQUISITION_METHOD = "acquisition_method";
  @XmlElement(name = "acquisition_method")
  private PoLineAcquisitionMethod acquisitionMethod;

  public static final String JSON_PROPERTY_NO_CHARGE = "no_charge";
  @XmlElement(name = "no_charge")
  private Boolean noCharge;

  public static final String JSON_PROPERTY_RUSH = "rush";
  @XmlElement(name = "rush")
  private Boolean rush;

  public static final String JSON_PROPERTY_CANCELLATION_RESTRICTION = "cancellation_restriction";
  @XmlElement(name = "cancellation_restriction")
  private Boolean cancellationRestriction;

  public static final String JSON_PROPERTY_CANCELLATION_RESTRICTION_NOTE = "cancellation_restriction_note";
  @XmlElement(name = "cancellation_restriction_note")
  private String cancellationRestrictionNote;

  public static final String JSON_PROPERTY_PRICE = "price";
  @XmlElement(name = "price")
  private Amount price;

  public static final String JSON_PROPERTY_DISCOUNT = "discount";
  @XmlElement(name = "discount")
  private String discount;

  public static final String JSON_PROPERTY_VENDOR_REFERENCE_NUMBER = "vendor_reference_number";
  @XmlElement(name = "vendor_reference_number")
  private String vendorReferenceNumber;

  public static final String JSON_PROPERTY_VENDOR_REFERENCE_NUMBER_TYPE = "vendor_reference_number_type";
  @XmlElement(name = "vendor_reference_number_type")
  private PoLineVendorReferenceNumberType vendorReferenceNumberType;

  public static final String JSON_PROPERTY_SOURCE_TYPE = "source_type";
  @XmlElement(name = "source_type")
  private PoLineSourceType sourceType;

  public static final String JSON_PROPERTY_PO_NUMBER = "po_number";
  @XmlElement(name = "po_number")
  private String poNumber;

  public static final String JSON_PROPERTY_INVOICE_REFERENCE = "invoice_reference";
  @XmlElement(name = "invoice_reference")
  private String invoiceReference;

  public static final String JSON_PROPERTY_RESOURCE_METADATA = "resource_metadata";
  @XmlElement(name = "resource_metadata")
  private ResourceMetadata resourceMetadata;

  public static final String JSON_PROPERTY_FUND_DISTRIBUTION = "fund_distribution";
  // Is a container wrapped=true
  // items.name=fundDistribution items.baseName=fundDistribution items.xmlName= items.xmlNamespace=
  // items.example= items.type=FundDistribution
  @XmlElement(name = "fundDistribution")
  @XmlElementWrapper(name = "fund_distributions")
  private List<FundDistribution> fundDistribution = null;

  public static final String JSON_PROPERTY_REPORTING_CODE = "reporting_code";
  @XmlElement(name = "reporting_code")
  private String reportingCode;

  public static final String JSON_PROPERTY_SECONDARY_REPORTING_CODE = "secondary_reporting_code";
  @XmlElement(name = "secondary_reporting_code")
  private String secondaryReportingCode;

  public static final String JSON_PROPERTY_TERTIARY_REPORTING_CODE = "tertiary_reporting_code";
  @XmlElement(name = "tertiary_reporting_code")
  private String tertiaryReportingCode;

  public static final String JSON_PROPERTY_VENDOR_NOTE = "vendor_note";
  @XmlElement(name = "vendor_note")
  private String vendorNote;

  public static final String JSON_PROPERTY_RECEIVING_NOTE = "receiving_note";
  @XmlElement(name = "receiving_note")
  private String receivingNote;

  public static final String JSON_PROPERTY_ALERT = "alert";
  // Is a container wrapped=true
  // items.name=alert items.baseName=alert items.xmlName=alert items.xmlNamespace=
  // items.example= items.type=Object
  @XmlElement(name = "alert")
  @XmlElementWrapper(name = "alerts")
  private List<String> alert = null;

  public static final String JSON_PROPERTY_NOTE = "note";
  // Is a container wrapped=true
  // items.name=note items.baseName=note items.xmlName= items.xmlNamespace=
  // items.example= items.type=Note2
  @XmlElement(name = "note")
  @XmlElementWrapper(name = "notes")
  private List<Note> note = null;

  public static final String JSON_PROPERTY_LOCATION = "location";
  // Is a container wrapped=true
  // items.name=location items.baseName=location items.xmlName= items.xmlNamespace=
  // items.example= items.type=Location2
  @XmlElement(name = "location")
  @XmlElementWrapper(name = "locations")
  private List<Location> location = null;

  public static final String JSON_PROPERTY_INTERESTED_USER = "interested_user";
  // Is a container wrapped=true
  // items.name=interestedUser items.baseName=interestedUser items.xmlName= items.xmlNamespace=
  // items.example= items.type=InterestedUser2
  @XmlElement(name = "interestedUser")
  @XmlElementWrapper(name = "interested_users")
  private List<InterestedUser> interestedUser = null;

  public static final String JSON_PROPERTY_LICENSE = "license";
  @XmlElement(name = "license")
  private PoLineLicense license;

  public static final String JSON_PROPERTY_ACCESS_MODEL = "access_model";
  @XmlElement(name = "access_model")
  private String accessModel;

  public static final String JSON_PROPERTY_URL = "url";
  @XmlElement(name = "url")
  private String url;

  /**
   * Gets or Sets baseStatus
   */
  public enum BaseStatusEnum {
    ACTIVE("ACTIVE"),
    
    INACTIVE("INACTIVE");

    private String value;

    BaseStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static BaseStatusEnum fromValue(String value) {
      for (BaseStatusEnum b : BaseStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_BASE_STATUS = "base_status";
  @XmlElement(name = "base_status")
  private BaseStatusEnum baseStatus;

  public static final String JSON_PROPERTY_ACCESS_PROVIDER = "access_provider";
  @XmlElement(name = "access_provider")
  private String accessProvider;

  public static final String JSON_PROPERTY_MANUAL_RENEWAL = "manual_renewal";
  @XmlElement(name = "manual_renewal")
  private Boolean manualRenewal;

  public static final String JSON_PROPERTY_RENEWAL_CYCLE = "renewal_cycle";
  @XmlElement(name = "renewal_cycle")
  private PoLineRenewalCycle renewalCycle;

  public static final String JSON_PROPERTY_SUBSCRIPTION_FROM_DATE = "subscription_from_date";
  @XmlElement(name = "subscription_from_date")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'Z'")
  private Date subscriptionFromDate;

  public static final String JSON_PROPERTY_SUBSCRIPTION_TO_DATE = "subscription_to_date";
  @XmlElement(name = "subscription_to_date")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'Z'")
  private Date subscriptionToDate;

  public static final String JSON_PROPERTY_RENEWAL_DATE = "renewal_date";
  @XmlElement(name = "renewal_date")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'Z'")
  private Date renewalDate;

  public static final String JSON_PROPERTY_RENEWAL_PERIOD = "renewal_period";
  @XmlElement(name = "renewal_period")
  private Integer renewalPeriod;

  public static final String JSON_PROPERTY_MATERIAL_TYPE = "material_type";
  @XmlElement(name = "material_type")
  private PoLineMaterialType materialType;

  public static final String JSON_PROPERTY_CREATED_DATE = "created_date";
  @XmlElement(name = "created_date")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'Z'")
  private Date createdDate;

  public static final String JSON_PROPERTY_STATUS_DATE = "status_date";
  @XmlElement(name = "status_date")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'Z'")
  private Date statusDate;

  public static final String JSON_PROPERTY_EXPECTED_RECEIPT_DATE = "expected_receipt_date";
  @XmlElement(name = "expected_receipt_date")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'Z'")
  private Date expectedReceiptDate;


  public PoLine link(String link) {
    
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(isAttribute = true, localName = "link")

  public String getLink() {
    return link;
  }


  public void setLink(String link) {
    this.link = link;
  }


  public PoLine number(String number) {
    
    this.number = number;
    return this;
  }

   /**
   * The PO line number. Output parameter. Should be used in subsequent queries regarding the PO line.
   * @return number
  **/
  
  @ApiModelProperty(example = "POL-10853", value = "The PO line number. Output parameter. Should be used in subsequent queries regarding the PO line.")
  @JsonProperty(JSON_PROPERTY_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "number")

  public String getNumber() {
    return number;
  }


  public void setNumber(String number) {
    this.number = number;
  }


  public PoLine status(PoLineStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "status")

  public PoLineStatus getStatus() {
    return status;
  }


  public void setStatus(PoLineStatus status) {
    this.status = status;
  }


  public PoLine owner(PoLineOwner owner) {
    
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "owner")

  public PoLineOwner getOwner() {
    return owner;
  }


  public void setOwner(PoLineOwner owner) {
    this.owner = owner;
  }


  public PoLine type(PoLineType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "type")

  public PoLineType getType() {
    return type;
  }


  public void setType(PoLineType type) {
    this.type = type;
  }


  public PoLine vendor(PoLineVendor vendor) {
    
    this.vendor = vendor;
    return this;
  }

   /**
   * Get vendor
   * @return vendor
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VENDOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "vendor")

  public PoLineVendor getVendor() {
    return vendor;
  }


  public void setVendor(PoLineVendor vendor) {
    this.vendor = vendor;
  }


  public PoLine vendorAccount(String vendorAccount) {
    
    this.vendorAccount = vendorAccount;
    return this;
  }

   /**
   * The vendor account code. Mandatory for processing the PO line. If not supplied, the PO line will be created as In Review. In the PUT action, a vendor account can be changed only before the PO line was attached to a PO (i.e. statuses: In Review, Deferred, Packaging).
   * @return vendorAccount
  **/
  
  @ApiModelProperty(example = "MVEN", value = "The vendor account code. Mandatory for processing the PO line. If not supplied, the PO line will be created as In Review. In the PUT action, a vendor account can be changed only before the PO line was attached to a PO (i.e. statuses: In Review, Deferred, Packaging).")
  @JsonProperty(JSON_PROPERTY_VENDOR_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "vendor_account")

  public String getVendorAccount() {
    return vendorAccount;
  }


  public void setVendorAccount(String vendorAccount) {
    this.vendorAccount = vendorAccount;
  }


  public PoLine reclaimInterval(String reclaimInterval) {
    
    this.reclaimInterval = reclaimInterval;
    return this;
  }

   /**
   * The number of days to wait before sending a 2nd, 3rd, 4th etc claim letter to the vendor. Optional. By default, this field will be populated based on the definitions on the vendor account.
   * @return reclaimInterval
  **/
  @ApiModelProperty(example = "1", required = true, value = "The number of days to wait before sending a 2nd, 3rd, 4th etc claim letter to the vendor. Optional. By default, this field will be populated based on the definitions on the vendor account.")
  @JsonProperty(JSON_PROPERTY_RECLAIM_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  @JacksonXmlProperty(localName = "reclaim_interval")

  public String getReclaimInterval() {
    return reclaimInterval;
  }


  public void setReclaimInterval(String reclaimInterval) {
    this.reclaimInterval = reclaimInterval;
  }


  public PoLine expectedReceiptInterval(String expectedReceiptInterval) {
    
    this.expectedReceiptInterval = expectedReceiptInterval;
    return this;
  }

   /**
   * Added to the current date. Default is from vendor account.
   * @return expectedReceiptInterval
  **/
  
  @ApiModelProperty(example = "1", value = "Added to the current date. Default is from vendor account.")
  @JsonProperty(JSON_PROPERTY_EXPECTED_RECEIPT_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "expected_receipt_interval")

  public String getExpectedReceiptInterval() {
    return expectedReceiptInterval;
  }


  public void setExpectedReceiptInterval(String expectedReceiptInterval) {
    this.expectedReceiptInterval = expectedReceiptInterval;
  }


  public PoLine claimingInterval(String claimingInterval) {
    
    this.claimingInterval = claimingInterval;
    return this;
  }

   /**
   * Added to the expected receipt date. Default is from vendor account.
   * @return claimingInterval
  **/
  
  @ApiModelProperty(example = "1", value = "Added to the expected receipt date. Default is from vendor account.")
  @JsonProperty(JSON_PROPERTY_CLAIMING_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "claiming_interval")

  public String getClaimingInterval() {
    return claimingInterval;
  }


  public void setClaimingInterval(String claimingInterval) {
    this.claimingInterval = claimingInterval;
  }


  public PoLine expectedActivationInterval(String expectedActivationInterval) {
    
    this.expectedActivationInterval = expectedActivationInterval;
    return this;
  }

   /**
   * Added to the current date. Default is from vendor account.
   * @return expectedActivationInterval
  **/
  
  @ApiModelProperty(example = "1", value = "Added to the current date. Default is from vendor account.")
  @JsonProperty(JSON_PROPERTY_EXPECTED_ACTIVATION_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "expected_activation_interval")

  public String getExpectedActivationInterval() {
    return expectedActivationInterval;
  }


  public void setExpectedActivationInterval(String expectedActivationInterval) {
    this.expectedActivationInterval = expectedActivationInterval;
  }


  public PoLine subscriptionInterval(String subscriptionInterval) {
    
    this.subscriptionInterval = subscriptionInterval;
    return this;
  }

   /**
   * Added to the expected activation date. Default is from vendor account.
   * @return subscriptionInterval
  **/
  
  @ApiModelProperty(example = "1", value = "Added to the expected activation date. Default is from vendor account.")
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "subscription_interval")

  public String getSubscriptionInterval() {
    return subscriptionInterval;
  }


  public void setSubscriptionInterval(String subscriptionInterval) {
    this.subscriptionInterval = subscriptionInterval;
  }


  public PoLine expectedActivationDate(Date expectedActivationDate) {
    
    this.expectedActivationDate = expectedActivationDate;
    return this;
  }

   /**
   * Added to expected activation date. Default is from vendor account.
   * @return expectedActivationDate
  **/
  
  @ApiModelProperty(value = "Added to expected activation date. Default is from vendor account.")
  @JsonProperty(JSON_PROPERTY_EXPECTED_ACTIVATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "expected_activation_date")

  public Date getExpectedActivationDate() {
    return expectedActivationDate;
  }


  public void setExpectedActivationDate(Date expectedActivationDate) {
    this.expectedActivationDate = expectedActivationDate;
  }


  public PoLine eActivationDueInterval(String eActivationDueInterval) {
    
    this.eActivationDueInterval = eActivationDueInterval;
    return this;
  }

   /**
   * Added to expected activation date. Default is from customer parameter.
   * @return eActivationDueInterval
  **/
  
  @ApiModelProperty(example = "1", value = "Added to expected activation date. Default is from customer parameter.")
  @JsonProperty(JSON_PROPERTY_E_ACTIVATION_DUE_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "e_activation_due_interval")

  public String geteActivationDueInterval() {
    return eActivationDueInterval;
  }


  public void seteActivationDueInterval(String eActivationDueInterval) {
    this.eActivationDueInterval = eActivationDueInterval;
  }


  public PoLine acquisitionMethod(PoLineAcquisitionMethod acquisitionMethod) {
    
    this.acquisitionMethod = acquisitionMethod;
    return this;
  }

   /**
   * Get acquisitionMethod
   * @return acquisitionMethod
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACQUISITION_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "acquisition_method")

  public PoLineAcquisitionMethod getAcquisitionMethod() {
    return acquisitionMethod;
  }


  public void setAcquisitionMethod(PoLineAcquisitionMethod acquisitionMethod) {
    this.acquisitionMethod = acquisitionMethod;
  }


  public PoLine noCharge(Boolean noCharge) {
    
    this.noCharge = noCharge;
    return this;
  }

   /**
   * Indication if the order is free of charge. Optional. Default is False. Relevant only for acquisition methods: Approval Plan, Purchase, Purchase at Vendor System.
   * @return noCharge
  **/
  
  @ApiModelProperty(example = "false", value = "Indication if the order is free of charge. Optional. Default is False. Relevant only for acquisition methods: Approval Plan, Purchase, Purchase at Vendor System.")
  @JsonProperty(JSON_PROPERTY_NO_CHARGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "no_charge")

  public Boolean getNoCharge() {
    return noCharge;
  }


  public void setNoCharge(Boolean noCharge) {
    this.noCharge = noCharge;
  }


  public PoLine rush(Boolean rush) {
    
    this.rush = rush;
    return this;
  }

   /**
   * Is it rush PO line. Optional. Default is False.
   * @return rush
  **/
  
  @ApiModelProperty(example = "false", value = "Is it rush PO line. Optional. Default is False.")
  @JsonProperty(JSON_PROPERTY_RUSH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "rush")

  public Boolean getRush() {
    return rush;
  }


  public void setRush(Boolean rush) {
    this.rush = rush;
  }


  public PoLine cancellationRestriction(Boolean cancellationRestriction) {
    
    this.cancellationRestriction = cancellationRestriction;
    return this;
  }

   /**
   * Indication whether the cancellation restriction note should display a warning upon the cancellation of a PO line. Optional. Default is False.
   * @return cancellationRestriction
  **/
  
  @ApiModelProperty(example = "false", value = "Indication whether the cancellation restriction note should display a warning upon the cancellation of a PO line. Optional. Default is False.")
  @JsonProperty(JSON_PROPERTY_CANCELLATION_RESTRICTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "cancellation_restriction")

  public Boolean getCancellationRestriction() {
    return cancellationRestriction;
  }


  public void setCancellationRestriction(Boolean cancellationRestriction) {
    this.cancellationRestriction = cancellationRestriction;
  }


  public PoLine cancellationRestrictionNote(String cancellationRestrictionNote) {
    
    this.cancellationRestrictionNote = cancellationRestrictionNote;
    return this;
  }

   /**
   * A warning to be displayed when canceling a PO line. Optional.
   * @return cancellationRestrictionNote
  **/
  
  @ApiModelProperty(value = "A warning to be displayed when canceling a PO line. Optional.")
  @JsonProperty(JSON_PROPERTY_CANCELLATION_RESTRICTION_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "cancellation_restriction_note")

  public String getCancellationRestrictionNote() {
    return cancellationRestrictionNote;
  }


  public void setCancellationRestrictionNote(String cancellationRestrictionNote) {
    this.cancellationRestrictionNote = cancellationRestrictionNote;
  }


  public PoLine price(Amount price) {
    
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "price")

  public Amount getPrice() {
    return price;
  }


  public void setPrice(Amount price) {
    this.price = price;
  }


  public PoLine discount(String discount) {
    
    this.discount = discount;
    return this;
  }

   /**
   * Discount (in percentage). In the POST action, the default for this field is the discount defined on the vendor account. Overriding vendor account&#39;s discount with discount 0 is currently not supported. Not supported with PUT action.
   * @return discount
  **/
  
  @ApiModelProperty(example = "20", value = "Discount (in percentage). In the POST action, the default for this field is the discount defined on the vendor account. Overriding vendor account's discount with discount 0 is currently not supported. Not supported with PUT action.")
  @JsonProperty(JSON_PROPERTY_DISCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "discount")

  public String getDiscount() {
    return discount;
  }


  public void setDiscount(String discount) {
    this.discount = discount;
  }


  public PoLine vendorReferenceNumber(String vendorReferenceNumber) {
    
    this.vendorReferenceNumber = vendorReferenceNumber;
    return this;
  }

   /**
   * The number given by the vendor to the PO line. Optional. If exists, it can be used for identifying the PO line.
   * @return vendorReferenceNumber
  **/
  
  @ApiModelProperty(example = "125", value = "The number given by the vendor to the PO line. Optional. If exists, it can be used for identifying the PO line.")
  @JsonProperty(JSON_PROPERTY_VENDOR_REFERENCE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "vendor_reference_number")

  public String getVendorReferenceNumber() {
    return vendorReferenceNumber;
  }


  public void setVendorReferenceNumber(String vendorReferenceNumber) {
    this.vendorReferenceNumber = vendorReferenceNumber;
  }


  public PoLine vendorReferenceNumberType(PoLineVendorReferenceNumberType vendorReferenceNumberType) {
    
    this.vendorReferenceNumberType = vendorReferenceNumberType;
    return this;
  }

   /**
   * Get vendorReferenceNumberType
   * @return vendorReferenceNumberType
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VENDOR_REFERENCE_NUMBER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "vendor_reference_number_type")

  public PoLineVendorReferenceNumberType getVendorReferenceNumberType() {
    return vendorReferenceNumberType;
  }


  public void setVendorReferenceNumberType(PoLineVendorReferenceNumberType vendorReferenceNumberType) {
    this.vendorReferenceNumberType = vendorReferenceNumberType;
  }


  public PoLine sourceType(PoLineSourceType sourceType) {
    
    this.sourceType = sourceType;
    return this;
  }

   /**
   * Get sourceType
   * @return sourceType
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "source_type")

  public PoLineSourceType getSourceType() {
    return sourceType;
  }


  public void setSourceType(PoLineSourceType sourceType) {
    this.sourceType = sourceType;
  }


  public PoLine poNumber(String poNumber) {
    
    this.poNumber = poNumber;
    return this;
  }

   /**
   * The PO number that this PO Line is packed into. Optional. If supplied in the POST action, and exists in Alma - then the newly created PO line will be linked to this PO. If not, the PO line will be linked to a PO when it will be packaged, according to the system&#39;s policy. In the PUT action, the po_number can be changed only before the PO line was attached to a PO (i.e. statuses: In Review, Deferred, Packaging).
   * @return poNumber
  **/
  
  @ApiModelProperty(example = "PO-254153", value = "The PO number that this PO Line is packed into. Optional. If supplied in the POST action, and exists in Alma - then the newly created PO line will be linked to this PO. If not, the PO line will be linked to a PO when it will be packaged, according to the system's policy. In the PUT action, the po_number can be changed only before the PO line was attached to a PO (i.e. statuses: In Review, Deferred, Packaging).")
  @JsonProperty(JSON_PROPERTY_PO_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "po_number")

  public String getPoNumber() {
    return poNumber;
  }


  public void setPoNumber(String poNumber) {
    this.poNumber = poNumber;
  }


  public PoLine invoiceReference(String invoiceReference) {
    
    this.invoiceReference = invoiceReference;
    return this;
  }

   /**
   * Invoice reference number, if exists. Optional. In the PUT action, the invoice can be changed only before the PO line was attached to a PO (i.e. statuses: In Review, Deferred, Packaging).
   * @return invoiceReference
  **/
  
  @ApiModelProperty(value = "Invoice reference number, if exists. Optional. In the PUT action, the invoice can be changed only before the PO line was attached to a PO (i.e. statuses: In Review, Deferred, Packaging).")
  @JsonProperty(JSON_PROPERTY_INVOICE_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "invoice_reference")

  public String getInvoiceReference() {
    return invoiceReference;
  }


  public void setInvoiceReference(String invoiceReference) {
    this.invoiceReference = invoiceReference;
  }


  public PoLine resourceMetadata(ResourceMetadata resourceMetadata) {
    
    this.resourceMetadata = resourceMetadata;
    return this;
  }

   /**
   * Get resourceMetadata
   * @return resourceMetadata
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_RESOURCE_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  @JacksonXmlProperty(localName = "resource_metadata")

  public ResourceMetadata getResourceMetadata() {
    return resourceMetadata;
  }


  public void setResourceMetadata(ResourceMetadata resourceMetadata) {
    this.resourceMetadata = resourceMetadata;
  }


  public PoLine fundDistribution(List<FundDistribution> fundDistribution) {
    
    this.fundDistribution = fundDistribution;
    return this;
  }

  public PoLine addFundDistributionItem(FundDistribution fundDistributionItem) {
    if (this.fundDistribution == null) {
      this.fundDistribution = new ArrayList<FundDistribution>();
    }
    this.fundDistribution.add(fundDistributionItem);
    return this;
  }

   /**
   * The Fund Distributions list. Mandatory for processing the invoice line. [Get funds API](https://developers.exlibrisgroup.com/alma/apis/acq/GET/gwPcGly021oUHLI4O/zpt8U7ewiJYRLM/d5b14609-b590-470e-baba-9944682f8c7e).
   * @return fundDistribution
  **/
  
  @ApiModelProperty(value = "The Fund Distributions list. Mandatory for processing the invoice line. [Get funds API](https://developers.exlibrisgroup.com/alma/apis/acq/GET/gwPcGly021oUHLI4O/zpt8U7ewiJYRLM/d5b14609-b590-470e-baba-9944682f8c7e).")
  @JsonProperty(JSON_PROPERTY_FUND_DISTRIBUTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=
  @JacksonXmlElementWrapper(useWrapping = true, localName = "fundDistribution")

  public List<FundDistribution> getFundDistribution() {
    return fundDistribution;
  }


  public void setFundDistribution(List<FundDistribution> fundDistribution) {
    this.fundDistribution = fundDistribution;
  }


  public PoLine reportingCode(String reportingCode) {
    
    this.reportingCode = reportingCode;
    return this;
  }

   /**
   * The related Reporting Code. Optional. Possible codes are listed in &#39;HFundsTransactionItem.reportingCode&#39; [code table](https://developers.exlibrisgroup.com/blog/Working-with-the-code-tables-API).
   * @return reportingCode
  **/
  
  @ApiModelProperty(example = "b", value = "The related Reporting Code. Optional. Possible codes are listed in 'HFundsTransactionItem.reportingCode' [code table](https://developers.exlibrisgroup.com/blog/Working-with-the-code-tables-API).")
  @JsonProperty(JSON_PROPERTY_REPORTING_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "reporting_code")

  public String getReportingCode() {
    return reportingCode;
  }


  public void setReportingCode(String reportingCode) {
    this.reportingCode = reportingCode;
  }


  public PoLine secondaryReportingCode(String secondaryReportingCode) {
    
    this.secondaryReportingCode = secondaryReportingCode;
    return this;
  }

   /**
   * Secondary reporting code. Optional. Possible values are listed in &#39;SecondReportingCode&#39; [code table](https://developers.exlibrisgroup.com/blog/Working-with-the-code-tables-API).
   * @return secondaryReportingCode
  **/
  
  @ApiModelProperty(example = "sso", value = "Secondary reporting code. Optional. Possible values are listed in 'SecondReportingCode' [code table](https://developers.exlibrisgroup.com/blog/Working-with-the-code-tables-API).")
  @JsonProperty(JSON_PROPERTY_SECONDARY_REPORTING_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "secondary_reporting_code")

  public String getSecondaryReportingCode() {
    return secondaryReportingCode;
  }


  public void setSecondaryReportingCode(String secondaryReportingCode) {
    this.secondaryReportingCode = secondaryReportingCode;
  }


  public PoLine tertiaryReportingCode(String tertiaryReportingCode) {
    
    this.tertiaryReportingCode = tertiaryReportingCode;
    return this;
  }

   /**
   * Tertiary reporting code. Optional. Possible values are listed in &#39;ThirdReportingCode&#39; [code table](https://developers.exlibrisgroup.com/blog/Working-with-the-code-tables-API).
   * @return tertiaryReportingCode
  **/
  
  @ApiModelProperty(example = "u", value = "Tertiary reporting code. Optional. Possible values are listed in 'ThirdReportingCode' [code table](https://developers.exlibrisgroup.com/blog/Working-with-the-code-tables-API).")
  @JsonProperty(JSON_PROPERTY_TERTIARY_REPORTING_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "tertiary_reporting_code")

  public String getTertiaryReportingCode() {
    return tertiaryReportingCode;
  }


  public void setTertiaryReportingCode(String tertiaryReportingCode) {
    this.tertiaryReportingCode = tertiaryReportingCode;
  }


  public PoLine vendorNote(String vendorNote) {
    
    this.vendorNote = vendorNote;
    return this;
  }

   /**
   * The vendor&#39;s note. Optional.
   * @return vendorNote
  **/
  
  @ApiModelProperty(value = "The vendor's note. Optional.")
  @JsonProperty(JSON_PROPERTY_VENDOR_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "vendor_note")

  public String getVendorNote() {
    return vendorNote;
  }


  public void setVendorNote(String vendorNote) {
    this.vendorNote = vendorNote;
  }


  public PoLine receivingNote(String receivingNote) {
    
    this.receivingNote = receivingNote;
    return this;
  }

   /**
   * The related receiving note. Optional.
   * @return receivingNote
  **/
  
  @ApiModelProperty(value = "The related receiving note. Optional.")
  @JsonProperty(JSON_PROPERTY_RECEIVING_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "receiving_note")

  public String getReceivingNote() {
    return receivingNote;
  }


  public void setReceivingNote(String receivingNote) {
    this.receivingNote = receivingNote;
  }


  public PoLine alert(List<String> alert) {
    
    this.alert = alert;
    return this;
  }

  public PoLine addAlertItem(String alertItem) {
    if (this.alert == null) {
      this.alert = new ArrayList<String>();
    }
    this.alert.add(alertItem);
    return this;
  }

   /**
   * List of Alerts that blocked the processing of the PO line. Output parameter.
   * @return alert
  **/
  
  @ApiModelProperty(value = "List of Alerts that blocked the processing of the PO line. Output parameter.")
  @JsonProperty(JSON_PROPERTY_ALERT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=alert
  @JacksonXmlElementWrapper(useWrapping = true, localName = "alert")

  public List<String> getAlert() {
    return alert;
  }


  public void setAlert(List<String> alert) {
    this.alert = alert;
  }


  public PoLine note(List<Note> note) {
    
    this.note = note;
    return this;
  }

  public PoLine addNoteItem(Note noteItem) {
    if (this.note == null) {
      this.note = new ArrayList<Note>();
    }
    this.note.add(noteItem);
    return this;
  }

   /**
   * List of the PO line related notes. In the PUT action the incoming list will replace the existing list. If the incoming list is empty, the existing list will be deleted.
   * @return note
  **/
  
  @ApiModelProperty(value = "List of the PO line related notes. In the PUT action the incoming list will replace the existing list. If the incoming list is empty, the existing list will be deleted.")
  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=
  @JacksonXmlElementWrapper(useWrapping = true, localName = "note")

  public List<Note> getNote() {
    return note;
  }


  public void setNote(List<Note> note) {
    this.note = note;
  }


  public PoLine location(List<Location> location) {
    
    this.location = location;
    return this;
  }

  public PoLine addLocationItem(Location locationItem) {
    if (this.location == null) {
      this.location = new ArrayList<Location>();
    }
    this.location.add(locationItem);
    return this;
  }

   /**
   * Information about the locations in which the ordered items will be stored. Relevant only for physical. See [Get locations API](https://developers.exlibrisgroup.com/alma/apis/conf/GET/gwPcGly021p29HpB7XTI4Dp4I8TKv6CAreHxJz3zVZbDL9ogrSqDbgE+r4q6vcJ0xBlD4LyRaVE&#x3D;/37088dc9-c685-4641-bc7f-60b5ca7cabed).
   * @return location
  **/
  
  @ApiModelProperty(value = "Information about the locations in which the ordered items will be stored. Relevant only for physical. See [Get locations API](https://developers.exlibrisgroup.com/alma/apis/conf/GET/gwPcGly021p29HpB7XTI4Dp4I8TKv6CAreHxJz3zVZbDL9ogrSqDbgE+r4q6vcJ0xBlD4LyRaVE=/37088dc9-c685-4641-bc7f-60b5ca7cabed).")
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=
  @JacksonXmlElementWrapper(useWrapping = true, localName = "location")

  public List<Location> getLocation() {
    return location;
  }


  public void setLocation(List<Location> location) {
    this.location = location;
  }


  public PoLine interestedUser(List<InterestedUser> interestedUser) {
    
    this.interestedUser = interestedUser;
    return this;
  }

  public PoLine addInterestedUserItem(InterestedUser interestedUserItem) {
    if (this.interestedUser == null) {
      this.interestedUser = new ArrayList<InterestedUser>();
    }
    this.interestedUser.add(interestedUserItem);
    return this;
  }

   /**
   * List of users to be annotated. With PUT if not sent will preserve the existing users.
   * @return interestedUser
  **/
  
  @ApiModelProperty(value = "List of users to be annotated. With PUT if not sent will preserve the existing users.")
  @JsonProperty(JSON_PROPERTY_INTERESTED_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=
  @JacksonXmlElementWrapper(useWrapping = true, localName = "interestedUser")

  public List<InterestedUser> getInterestedUser() {
    return interestedUser;
  }


  public void setInterestedUser(List<InterestedUser> interestedUser) {
    this.interestedUser = interestedUser;
  }


  public PoLine license(PoLineLicense license) {
    
    this.license = license;
    return this;
  }

   /**
   * Get license
   * @return license
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LICENSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "license")

  public PoLineLicense getLicense() {
    return license;
  }


  public void setLicense(PoLineLicense license) {
    this.license = license;
  }


  public PoLine accessModel(String accessModel) {
    
    this.accessModel = accessModel;
    return this;
  }

   /**
   * Relevant when PO Line type is Electronic and the Access Model is defined in the New Order API Integration Profile. It will be appended as a public note in the created electronic resource.
   * @return accessModel
  **/
  
  @ApiModelProperty(example = "unlimited", value = "Relevant when PO Line type is Electronic and the Access Model is defined in the New Order API Integration Profile. It will be appended as a public note in the created electronic resource.")
  @JsonProperty(JSON_PROPERTY_ACCESS_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "access_model")

  public String getAccessModel() {
    return accessModel;
  }


  public void setAccessModel(String accessModel) {
    this.accessModel = accessModel;
  }


  public PoLine url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * URL for E-book item.
   * @return url
  **/
  
  @ApiModelProperty(value = "URL for E-book item.")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "url")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public PoLine baseStatus(BaseStatusEnum baseStatus) {
    
    this.baseStatus = baseStatus;
    return this;
  }

   /**
   * Get baseStatus
   * @return baseStatus
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BASE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "base_status")

  public BaseStatusEnum getBaseStatus() {
    return baseStatus;
  }


  public void setBaseStatus(BaseStatusEnum baseStatus) {
    this.baseStatus = baseStatus;
  }


  public PoLine accessProvider(String accessProvider) {
    
    this.accessProvider = accessProvider;
    return this;
  }

   /**
   * Service Provider for E-book item. Relevant only for Electronic. In the PUT action, the access_provider can be changed only before the PO line was attached to a PO (i.e. statuses: In Review, Deferred, Packaging).
   * @return accessProvider
  **/
  
  @ApiModelProperty(value = "Service Provider for E-book item. Relevant only for Electronic. In the PUT action, the access_provider can be changed only before the PO line was attached to a PO (i.e. statuses: In Review, Deferred, Packaging).")
  @JsonProperty(JSON_PROPERTY_ACCESS_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "access_provider")

  public String getAccessProvider() {
    return accessProvider;
  }


  public void setAccessProvider(String accessProvider) {
    this.accessProvider = accessProvider;
  }


  public PoLine manualRenewal(Boolean manualRenewal) {
    
    this.manualRenewal = manualRenewal;
    return this;
  }

   /**
   * Indication if the renewal is done manually. Optional. Default is True. Relevant only for continuous and standing orders PO lines.
   * @return manualRenewal
  **/
  
  @ApiModelProperty(example = "false", value = "Indication if the renewal is done manually. Optional. Default is True. Relevant only for continuous and standing orders PO lines.")
  @JsonProperty(JSON_PROPERTY_MANUAL_RENEWAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "manual_renewal")

  public Boolean getManualRenewal() {
    return manualRenewal;
  }


  public void setManualRenewal(Boolean manualRenewal) {
    this.manualRenewal = manualRenewal;
  }


  public PoLine renewalCycle(PoLineRenewalCycle renewalCycle) {
    
    this.renewalCycle = renewalCycle;
    return this;
  }

   /**
   * Get renewalCycle
   * @return renewalCycle
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RENEWAL_CYCLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "renewal_cycle")

  public PoLineRenewalCycle getRenewalCycle() {
    return renewalCycle;
  }


  public void setRenewalCycle(PoLineRenewalCycle renewalCycle) {
    this.renewalCycle = renewalCycle;
  }


  public PoLine subscriptionFromDate(Date subscriptionFromDate) {
    
    this.subscriptionFromDate = subscriptionFromDate;
    return this;
  }

   /**
   * The date that the subscription for the PO line began. Optional. Relevant only for continuous and standing orders PO lines.
   * @return subscriptionFromDate
  **/
  
  @ApiModelProperty(value = "The date that the subscription for the PO line began. Optional. Relevant only for continuous and standing orders PO lines.")
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION_FROM_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "subscription_from_date")

  public Date getSubscriptionFromDate() {
    return subscriptionFromDate;
  }


  public void setSubscriptionFromDate(Date subscriptionFromDate) {
    this.subscriptionFromDate = subscriptionFromDate;
  }


  public PoLine subscriptionToDate(Date subscriptionToDate) {
    
    this.subscriptionToDate = subscriptionToDate;
    return this;
  }

   /**
   * The the last day of the subscription for the PO line. Optional. Relevant only for continuous and standing orders PO lines.
   * @return subscriptionToDate
  **/
  
  @ApiModelProperty(value = "The the last day of the subscription for the PO line. Optional. Relevant only for continuous and standing orders PO lines.")
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION_TO_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "subscription_to_date")

  public Date getSubscriptionToDate() {
    return subscriptionToDate;
  }


  public void setSubscriptionToDate(Date subscriptionToDate) {
    this.subscriptionToDate = subscriptionToDate;
  }


  public PoLine renewalDate(Date renewalDate) {
    
    this.renewalDate = renewalDate;
    return this;
  }

   /**
   * The the date of renewal. Relevant and mandatory only for continuous and standing orders PO lines. If not supplied, the PO line will be created as In Review.
   * @return renewalDate
  **/
  
  @ApiModelProperty(value = "The the date of renewal. Relevant and mandatory only for continuous and standing orders PO lines. If not supplied, the PO line will be created as In Review.")
  @JsonProperty(JSON_PROPERTY_RENEWAL_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "renewal_date")

  public Date getRenewalDate() {
    return renewalDate;
  }


  public void setRenewalDate(Date renewalDate) {
    this.renewalDate = renewalDate;
  }


  public PoLine renewalPeriod(Integer renewalPeriod) {
    
    this.renewalPeriod = renewalPeriod;
    return this;
  }

   /**
   * The number of days before the renewal date to be reminded. Optional. Default is 0. Relevant only for continuous and standing orders PO lines.
   * @return renewalPeriod
  **/
  
  @ApiModelProperty(example = "100", value = "The number of days before the renewal date to be reminded. Optional. Default is 0. Relevant only for continuous and standing orders PO lines.")
  @JsonProperty(JSON_PROPERTY_RENEWAL_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "renewal_period")

  public Integer getRenewalPeriod() {
    return renewalPeriod;
  }


  public void setRenewalPeriod(Integer renewalPeriod) {
    this.renewalPeriod = renewalPeriod;
  }


  public PoLine materialType(PoLineMaterialType materialType) {
    
    this.materialType = materialType;
    return this;
  }

   /**
   * Get materialType
   * @return materialType
  **/
  
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MATERIAL_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "material_type")

  public PoLineMaterialType getMaterialType() {
    return materialType;
  }


  public void setMaterialType(PoLineMaterialType materialType) {
    this.materialType = materialType;
  }


  public PoLine createdDate(Date createdDate) {
    
    this.createdDate = createdDate;
    return this;
  }

   /**
   * The creation date of the PO line.
   * @return createdDate
  **/
  
  @ApiModelProperty(value = "The creation date of the PO line.")
  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "created_date")

  public Date getCreatedDate() {
    return createdDate;
  }


  public void setCreatedDate(Date createdDate) {
    this.createdDate = createdDate;
  }


  public PoLine statusDate(Date statusDate) {
    
    this.statusDate = statusDate;
    return this;
  }

   /**
   * The date in which the PO line status was last updated.
   * @return statusDate
  **/
  
  @ApiModelProperty(value = "The date in which the PO line status was last updated.")
  @JsonProperty(JSON_PROPERTY_STATUS_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "status_date")

  public Date getStatusDate() {
    return statusDate;
  }


  public void setStatusDate(Date statusDate) {
    this.statusDate = statusDate;
  }


  public PoLine expectedReceiptDate(Date expectedReceiptDate) {
    
    this.expectedReceiptDate = expectedReceiptDate;
    return this;
  }

   /**
   * The date in which the po line is expected to be received at the library. If not specify, Alma will calculate estimation when the request will be sent to the vendor.
   * @return expectedReceiptDate
  **/
  
  @ApiModelProperty(value = "The date in which the po line is expected to be received at the library. If not specify, Alma will calculate estimation when the request will be sent to the vendor.")
  @JsonProperty(JSON_PROPERTY_EXPECTED_RECEIPT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "expected_receipt_date")

  public Date getExpectedReceiptDate() {
    return expectedReceiptDate;
  }


  public void setExpectedReceiptDate(Date expectedReceiptDate) {
    this.expectedReceiptDate = expectedReceiptDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoLine poLine = (PoLine) o;
    return Objects.equals(this.link, poLine.link) &&
        Objects.equals(this.number, poLine.number) &&
        Objects.equals(this.status, poLine.status) &&
        Objects.equals(this.owner, poLine.owner) &&
        Objects.equals(this.type, poLine.type) &&
        Objects.equals(this.vendor, poLine.vendor) &&
        Objects.equals(this.vendorAccount, poLine.vendorAccount) &&
        Objects.equals(this.reclaimInterval, poLine.reclaimInterval) &&
        Objects.equals(this.expectedReceiptInterval, poLine.expectedReceiptInterval) &&
        Objects.equals(this.claimingInterval, poLine.claimingInterval) &&
        Objects.equals(this.expectedActivationInterval, poLine.expectedActivationInterval) &&
        Objects.equals(this.subscriptionInterval, poLine.subscriptionInterval) &&
        Objects.equals(this.expectedActivationDate, poLine.expectedActivationDate) &&
        Objects.equals(this.eActivationDueInterval, poLine.eActivationDueInterval) &&
        Objects.equals(this.acquisitionMethod, poLine.acquisitionMethod) &&
        Objects.equals(this.noCharge, poLine.noCharge) &&
        Objects.equals(this.rush, poLine.rush) &&
        Objects.equals(this.cancellationRestriction, poLine.cancellationRestriction) &&
        Objects.equals(this.cancellationRestrictionNote, poLine.cancellationRestrictionNote) &&
        Objects.equals(this.price, poLine.price) &&
        Objects.equals(this.discount, poLine.discount) &&
        Objects.equals(this.vendorReferenceNumber, poLine.vendorReferenceNumber) &&
        Objects.equals(this.vendorReferenceNumberType, poLine.vendorReferenceNumberType) &&
        Objects.equals(this.sourceType, poLine.sourceType) &&
        Objects.equals(this.poNumber, poLine.poNumber) &&
        Objects.equals(this.invoiceReference, poLine.invoiceReference) &&
        Objects.equals(this.resourceMetadata, poLine.resourceMetadata) &&
        Objects.equals(this.fundDistribution, poLine.fundDistribution) &&
        Objects.equals(this.reportingCode, poLine.reportingCode) &&
        Objects.equals(this.secondaryReportingCode, poLine.secondaryReportingCode) &&
        Objects.equals(this.tertiaryReportingCode, poLine.tertiaryReportingCode) &&
        Objects.equals(this.vendorNote, poLine.vendorNote) &&
        Objects.equals(this.receivingNote, poLine.receivingNote) &&
        Objects.equals(this.alert, poLine.alert) &&
        Objects.equals(this.note, poLine.note) &&
        Objects.equals(this.location, poLine.location) &&
        Objects.equals(this.interestedUser, poLine.interestedUser) &&
        Objects.equals(this.license, poLine.license) &&
        Objects.equals(this.accessModel, poLine.accessModel) &&
        Objects.equals(this.url, poLine.url) &&
        Objects.equals(this.baseStatus, poLine.baseStatus) &&
        Objects.equals(this.accessProvider, poLine.accessProvider) &&
        Objects.equals(this.manualRenewal, poLine.manualRenewal) &&
        Objects.equals(this.renewalCycle, poLine.renewalCycle) &&
        Objects.equals(this.subscriptionFromDate, poLine.subscriptionFromDate) &&
        Objects.equals(this.subscriptionToDate, poLine.subscriptionToDate) &&
        Objects.equals(this.renewalDate, poLine.renewalDate) &&
        Objects.equals(this.renewalPeriod, poLine.renewalPeriod) &&
        Objects.equals(this.materialType, poLine.materialType) &&
        Objects.equals(this.createdDate, poLine.createdDate) &&
        Objects.equals(this.statusDate, poLine.statusDate) &&
        Objects.equals(this.expectedReceiptDate, poLine.expectedReceiptDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(link, number, status, owner, type, vendor, vendorAccount, reclaimInterval, expectedReceiptInterval, claimingInterval, expectedActivationInterval, subscriptionInterval, expectedActivationDate, eActivationDueInterval, acquisitionMethod, noCharge, rush, cancellationRestriction, cancellationRestrictionNote, price, discount, vendorReferenceNumber, vendorReferenceNumberType, sourceType, poNumber, invoiceReference, resourceMetadata, fundDistribution, reportingCode, secondaryReportingCode, tertiaryReportingCode, vendorNote, receivingNote, alert, note, location, interestedUser, license, accessModel, url, baseStatus, accessProvider, manualRenewal, renewalCycle, subscriptionFromDate, subscriptionToDate, renewalDate, renewalPeriod, materialType, createdDate, statusDate, expectedReceiptDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoLine2 {\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    vendor: ").append(toIndentedString(vendor)).append("\n");
    sb.append("    vendorAccount: ").append(toIndentedString(vendorAccount)).append("\n");
    sb.append("    reclaimInterval: ").append(toIndentedString(reclaimInterval)).append("\n");
    sb.append("    expectedReceiptInterval: ").append(toIndentedString(expectedReceiptInterval)).append("\n");
    sb.append("    claimingInterval: ").append(toIndentedString(claimingInterval)).append("\n");
    sb.append("    expectedActivationInterval: ").append(toIndentedString(expectedActivationInterval)).append("\n");
    sb.append("    subscriptionInterval: ").append(toIndentedString(subscriptionInterval)).append("\n");
    sb.append("    expectedActivationDate: ").append(toIndentedString(expectedActivationDate)).append("\n");
    sb.append("    eActivationDueInterval: ").append(toIndentedString(eActivationDueInterval)).append("\n");
    sb.append("    acquisitionMethod: ").append(toIndentedString(acquisitionMethod)).append("\n");
    sb.append("    noCharge: ").append(toIndentedString(noCharge)).append("\n");
    sb.append("    rush: ").append(toIndentedString(rush)).append("\n");
    sb.append("    cancellationRestriction: ").append(toIndentedString(cancellationRestriction)).append("\n");
    sb.append("    cancellationRestrictionNote: ").append(toIndentedString(cancellationRestrictionNote)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    vendorReferenceNumber: ").append(toIndentedString(vendorReferenceNumber)).append("\n");
    sb.append("    vendorReferenceNumberType: ").append(toIndentedString(vendorReferenceNumberType)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    poNumber: ").append(toIndentedString(poNumber)).append("\n");
    sb.append("    invoiceReference: ").append(toIndentedString(invoiceReference)).append("\n");
    sb.append("    resourceMetadata: ").append(toIndentedString(resourceMetadata)).append("\n");
    sb.append("    fundDistribution: ").append(toIndentedString(fundDistribution)).append("\n");
    sb.append("    reportingCode: ").append(toIndentedString(reportingCode)).append("\n");
    sb.append("    secondaryReportingCode: ").append(toIndentedString(secondaryReportingCode)).append("\n");
    sb.append("    tertiaryReportingCode: ").append(toIndentedString(tertiaryReportingCode)).append("\n");
    sb.append("    vendorNote: ").append(toIndentedString(vendorNote)).append("\n");
    sb.append("    receivingNote: ").append(toIndentedString(receivingNote)).append("\n");
    sb.append("    alert: ").append(toIndentedString(alert)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    interestedUser: ").append(toIndentedString(interestedUser)).append("\n");
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    accessModel: ").append(toIndentedString(accessModel)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    baseStatus: ").append(toIndentedString(baseStatus)).append("\n");
    sb.append("    accessProvider: ").append(toIndentedString(accessProvider)).append("\n");
    sb.append("    manualRenewal: ").append(toIndentedString(manualRenewal)).append("\n");
    sb.append("    renewalCycle: ").append(toIndentedString(renewalCycle)).append("\n");
    sb.append("    subscriptionFromDate: ").append(toIndentedString(subscriptionFromDate)).append("\n");
    sb.append("    subscriptionToDate: ").append(toIndentedString(subscriptionToDate)).append("\n");
    sb.append("    renewalDate: ").append(toIndentedString(renewalDate)).append("\n");
    sb.append("    renewalPeriod: ").append(toIndentedString(renewalPeriod)).append("\n");
    sb.append("    materialType: ").append(toIndentedString(materialType)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    statusDate: ").append(toIndentedString(statusDate)).append("\n");
    sb.append("    expectedReceiptDate: ").append(toIndentedString(expectedReceiptDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

