/*
 * Ex Libris APIs
 * For more information on how to use these APIs, including how to create an API key required for authentication, see [Alma REST APIs](https://developers.exlibrisgroup.com/alma/apis).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.unidue.ub.alma.shared.acq;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import javax.xml.bind.annotation.*;

/**
 * Vendor Object.
 */
@ApiModel(description = "Vendor Object.")
@JsonPropertyOrder({
  Vendor.JSON_PROPERTY_LINK,
  Vendor.JSON_PROPERTY_CODE,
  Vendor.JSON_PROPERTY_NAME,
  Vendor.JSON_PROPERTY_ADDITIONAL_CODE,
  Vendor.JSON_PROPERTY_FINANCIAL_SYS_CODE,
  Vendor.JSON_PROPERTY_NATIONAL_TAX_ID,
  Vendor.JSON_PROPERTY_STATUS,
  Vendor.JSON_PROPERTY_LIABLE_FOR_VAT,
  Vendor.JSON_PROPERTY_LANGUAGE,
  Vendor.JSON_PROPERTY_MATERIAL_SUPPLIER,
  Vendor.JSON_PROPERTY_ACCESS_PROVIDER,
  Vendor.JSON_PROPERTY_LICENSOR,
  Vendor.JSON_PROPERTY_GOVERNMENTAL,
  Vendor.JSON_PROPERTY_TAX_PERCENTAGE,
  Vendor.JSON_PROPERTY_LIBRARY,
  Vendor.JSON_PROPERTY_CURRENCY,
  Vendor.JSON_PROPERTY_ACCOUNT,
  Vendor.JSON_PROPERTY_CONTACT_PERSON,
  Vendor.JSON_PROPERTY_INTERFACE,
  Vendor.JSON_PROPERTY_CONTACT_INFO,
  Vendor.JSON_PROPERTY_EDI_INFO,
  Vendor.JSON_PROPERTY_NOTES
})

@XmlRootElement(name = "vendor")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "vendor")
public class Vendor implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_LINK = "link";
  @XmlAttribute(name = "link")
  private String link;

  public static final String JSON_PROPERTY_CODE = "code";
  @XmlElement(name = "code")
  private String code;

  public static final String JSON_PROPERTY_NAME = "name";
  @XmlElement(name = "name")
  private String name;

  public static final String JSON_PROPERTY_ADDITIONAL_CODE = "additional_code";
  @XmlElement(name = "additional_code")
  private String additionalCode;

  public static final String JSON_PROPERTY_FINANCIAL_SYS_CODE = "financial_sys_code";
  @XmlElement(name = "financial_sys_code")
  private String financialSysCode;

  public static final String JSON_PROPERTY_NATIONAL_TAX_ID = "national_tax_id";
  @XmlElement(name = "national_tax_id")
  private String nationalTaxId;

  public static final String JSON_PROPERTY_STATUS = "status";
  @XmlElement(name = "status")
  private VendorStatus status;

  public static final String JSON_PROPERTY_LIABLE_FOR_VAT = "liable_for_vat";
  @XmlElement(name = "liable_for_vat")
  private Boolean liableForVat;

  public static final String JSON_PROPERTY_LANGUAGE = "language";
  @XmlElement(name = "language")
  private VendorLanguage language;

  public static final String JSON_PROPERTY_MATERIAL_SUPPLIER = "material_supplier";
  @XmlElement(name = "material_supplier")
  private Boolean materialSupplier;

  public static final String JSON_PROPERTY_ACCESS_PROVIDER = "access_provider";
  @XmlElement(name = "access_provider")
  private Boolean accessProvider;

  public static final String JSON_PROPERTY_LICENSOR = "licensor";
  @XmlElement(name = "licensor")
  private Boolean licensor;

  public static final String JSON_PROPERTY_GOVERNMENTAL = "governmental";
  @XmlElement(name = "governmental")
  private Boolean governmental;

  public static final String JSON_PROPERTY_TAX_PERCENTAGE = "tax_percentage";
  @XmlElement(name = "tax_percentage")
  private String taxPercentage;

  public static final String JSON_PROPERTY_LIBRARY = "library";
  // Is a container wrapped=true
  // items.name=library items.baseName=library items.xmlName= items.xmlNamespace=
  // items.example= items.type=Library2
  @XmlElement(name = "library")
  @XmlElementWrapper(name = "libraries")
  private List<Library> library = null;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  // Is a container wrapped=true
  // items.name=currency items.baseName=currency items.xmlName=currency items.xmlNamespace=
  // items.example= items.type=Object
  @XmlElement(name = "currency")
  @XmlElementWrapper(name = "currencies")
  private List<InvoiceCurrency> currency = null;

  public static final String JSON_PROPERTY_ACCOUNT = "account";
  // Is a container wrapped=true
  // items.name=account items.baseName=account items.xmlName= items.xmlNamespace=
  // items.example= items.type=Account2
  @XmlElement(name = "account")
  @XmlElementWrapper(name = "accounts")
  private List<Account> account = null;

  public static final String JSON_PROPERTY_CONTACT_PERSON = "contact_person";
  // Is a container wrapped=true
  // items.name=contactPerson items.baseName=contactPerson items.xmlName= items.xmlNamespace=
  // items.example= items.type=ContactPerson
  @XmlElement(name = "contactPerson")
  @XmlElementWrapper(name = "contact_persons")
  private List<ContactPerson> contactPerson = null;

  public static final String JSON_PROPERTY_INTERFACE = "interface";
  // Is a container wrapped=true
  // items.name=_interface items.baseName=_interface items.xmlName= items.xmlNamespace=
  // items.example= items.type=Interface2
  @XmlElement(name = "_interface")
  @XmlElementWrapper(name = "interfaces")
  private List<AlmaInterface> _interface = null;

  public static final String JSON_PROPERTY_CONTACT_INFO = "contact_info";
  @XmlElement(name = "contact_info")
  private ContactInfo contactInfo;

  public static final String JSON_PROPERTY_EDI_INFO = "edi_info";
  @XmlElement(name = "edi_info")
  private EdiInfo ediInfo;

  public static final String JSON_PROPERTY_NOTES = "notes";
  @XmlElement(name = "notes")
  private Object notes = null;


  public Vendor link(String link) {
    
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(isAttribute = true, localName = "link")

  public String getLink() {
    return link;
  }


  public void setLink(String link) {
    this.link = link;
  }


  public Vendor code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * The vendor code. Mandatory.
   * @return code
  **/
  @ApiModelProperty(example = "BKHS", required = true, value = "The vendor code. Mandatory.")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  @JacksonXmlProperty(localName = "code")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public Vendor name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The vendor name. Mandatory.
   * @return name
  **/
  @ApiModelProperty(example = "The Bookhouse, Inc.", required = true, value = "The vendor name. Mandatory.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  @JacksonXmlProperty(localName = "name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Vendor additionalCode(String additionalCode) {
    
    this.additionalCode = additionalCode;
    return this;
  }

   /**
   * The vendor additional code.
   * @return additionalCode
  **/

  @ApiModelProperty(example = "10210102218", value = "The vendor additional code.")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "additional_code")

  public String getAdditionalCode() {
    return additionalCode;
  }


  public void setAdditionalCode(String additionalCode) {
    this.additionalCode = additionalCode;
  }


  public Vendor financialSysCode(String financialSysCode) {
    
    this.financialSysCode = financialSysCode;
    return this;
  }

   /**
   * A code for the financial system account.
   * @return financialSysCode
  **/

  @ApiModelProperty(example = "1", value = "A code for the financial system account.")
  @JsonProperty(JSON_PROPERTY_FINANCIAL_SYS_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "financial_sys_code")

  public String getFinancialSysCode() {
    return financialSysCode;
  }


  public void setFinancialSysCode(String financialSysCode) {
    this.financialSysCode = financialSysCode;
  }


  public Vendor nationalTaxId(String nationalTaxId) {
    
    this.nationalTaxId = nationalTaxId;
    return this;
  }

   /**
   * The vendor&#39;s a national tax ID number.
   * @return nationalTaxId
  **/

  @ApiModelProperty(example = "3", value = "The vendor's a national tax ID number.")
  @JsonProperty(JSON_PROPERTY_NATIONAL_TAX_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "national_tax_id")

  public String getNationalTaxId() {
    return nationalTaxId;
  }


  public void setNationalTaxId(String nationalTaxId) {
    this.nationalTaxId = nationalTaxId;
  }


  public Vendor status(VendorStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "status")

  public VendorStatus getStatus() {
    return status;
  }


  public void setStatus(VendorStatus status) {
    this.status = status;
  }


  public Vendor liableForVat(Boolean liableForVat) {
    
    this.liableForVat = liableForVat;
    return this;
  }

   /**
   * Indication if invoices must be paid with VAT included. For Governmental vendor, this field must be set to true in order to collect VAT for an invoice.
   * @return liableForVat
  **/

  @ApiModelProperty(example = "false", value = "Indication if invoices must be paid with VAT included. For Governmental vendor, this field must be set to true in order to collect VAT for an invoice.")
  @JsonProperty(JSON_PROPERTY_LIABLE_FOR_VAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "liable_for_vat")

  public Boolean getLiableForVat() {
    return liableForVat;
  }


  public void setLiableForVat(Boolean liableForVat) {
    this.liableForVat = liableForVat;
  }


  public Vendor language(VendorLanguage language) {
    
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "language")

  public VendorLanguage getLanguage() {
    return language;
  }


  public void setLanguage(VendorLanguage language) {
    this.language = language;
  }


  public Vendor materialSupplier(Boolean materialSupplier) {
    
    this.materialSupplier = materialSupplier;
    return this;
  }

   /**
   * Indication if the vendor is a material_supplier. Mandatory when creating a vendor. At least one of the following fields must be true: material_supplier, access_provider, licensor, governmental.
   * @return materialSupplier
  **/

  @ApiModelProperty(example = "true", value = "Indication if the vendor is a material_supplier. Mandatory when creating a vendor. At least one of the following fields must be true: material_supplier, access_provider, licensor, governmental.")
  @JsonProperty(JSON_PROPERTY_MATERIAL_SUPPLIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "material_supplier")

  public Boolean getMaterialSupplier() {
    return materialSupplier;
  }


  public void setMaterialSupplier(Boolean materialSupplier) {
    this.materialSupplier = materialSupplier;
  }


  public Vendor accessProvider(Boolean accessProvider) {
    
    this.accessProvider = accessProvider;
    return this;
  }

   /**
   * Indication if the vendor is a access_provider. Mandatory when creating a vendor. At least one of the following fields must be true: material_supplier, access_provider, licensor, governmental.
   * @return accessProvider
  **/

  @ApiModelProperty(example = "false", value = "Indication if the vendor is a access_provider. Mandatory when creating a vendor. At least one of the following fields must be true: material_supplier, access_provider, licensor, governmental.")
  @JsonProperty(JSON_PROPERTY_ACCESS_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "access_provider")

  public Boolean getAccessProvider() {
    return accessProvider;
  }


  public void setAccessProvider(Boolean accessProvider) {
    this.accessProvider = accessProvider;
  }


  public Vendor licensor(Boolean licensor) {
    
    this.licensor = licensor;
    return this;
  }

   /**
   * Indication if the vendor is a licensor. Mandatory when creating a vendor. At least one of the following fields must be true: material_supplier, access_provider, licensor, governmental.
   * @return licensor
  **/

  @ApiModelProperty(example = "false", value = "Indication if the vendor is a licensor. Mandatory when creating a vendor. At least one of the following fields must be true: material_supplier, access_provider, licensor, governmental.")
  @JsonProperty(JSON_PROPERTY_LICENSOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "licensor")

  public Boolean getLicensor() {
    return licensor;
  }


  public void setLicensor(Boolean licensor) {
    this.licensor = licensor;
  }


  public Vendor governmental(Boolean governmental) {
    
    this.governmental = governmental;
    return this;
  }

   /**
   * Indication if the vendor is a governmental. Mandatory when creating a vendor. At least one of the following fields must be true: material_supplier, access_provider, licensor, governmental. If Governmental is true, material_supplier, access_provider and licensor must be false.
   * @return governmental
  **/

  @ApiModelProperty(example = "false", value = "Indication if the vendor is a governmental. Mandatory when creating a vendor. At least one of the following fields must be true: material_supplier, access_provider, licensor, governmental. If Governmental is true, material_supplier, access_provider and licensor must be false.")
  @JsonProperty(JSON_PROPERTY_GOVERNMENTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "governmental")

  public Boolean getGovernmental() {
    return governmental;
  }


  public void setGovernmental(Boolean governmental) {
    this.governmental = governmental;
  }


  public Vendor taxPercentage(String taxPercentage) {
    
    this.taxPercentage = taxPercentage;
    return this;
  }

   /**
   * A numerical value for the tax to be administered. Relevant only for governmental vendor.
   * @return taxPercentage
  **/

  @ApiModelProperty(value = "A numerical value for the tax to be administered. Relevant only for governmental vendor.")
  @JsonProperty(JSON_PROPERTY_TAX_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "tax_percentage")

  public String getTaxPercentage() {
    return taxPercentage;
  }


  public void setTaxPercentage(String taxPercentage) {
    this.taxPercentage = taxPercentage;
  }


  public Vendor library(List<Library> library) {
    
    this.library = library;
    return this;
  }

  public Vendor addLibraryItem(Library libraryItem) {
    if (this.library == null) {
      this.library = new ArrayList<Library>();
    }
    this.library.add(libraryItem);
    return this;
  }

   /**
   * List of libraries related to the vendor or the account. If not specified, the default will be the institution including all sub units.
   * @return library
  **/

  @ApiModelProperty(value = "List of libraries related to the vendor or the account. If not specified, the default will be the institution including all sub units.")
  @JsonProperty(JSON_PROPERTY_LIBRARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=
  @JacksonXmlElementWrapper(useWrapping = true, localName = "library")

  public List<Library> getLibrary() {
    return library;
  }


  public void setLibrary(List<Library> library) {
    this.library = library;
  }


  public Vendor currency(List<InvoiceCurrency> currency) {
    
    this.currency = currency;
    return this;
  }

  public Vendor addCurrencyItem(InvoiceCurrency currencyItem) {
    if (this.currency == null) {
      this.currency = new ArrayList<>();
    }
    this.currency.add(currencyItem);
    return this;
  }

   /**
   * List of currencies with which the vendor operates. If not specified, all the institution&#39;s supported currencies will be considered as supported.
   * @return currency
  **/

  @ApiModelProperty(value = "List of currencies with which the vendor operates. If not specified, all the institution's supported currencies will be considered as supported.")
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=currency
  @JacksonXmlElementWrapper(useWrapping = true, localName = "currency")

  public List<InvoiceCurrency> getCurrency() {
    return currency;
  }


  public void setCurrency(List<InvoiceCurrency> currency) {
    this.currency = currency;
  }


  public Vendor account(List<Account> account) {
    
    this.account = account;
    return this;
  }

  public Vendor addAccountItem(Account accountItem) {
    if (this.account == null) {
      this.account = new ArrayList<Account>();
    }
    this.account.add(accountItem);
    return this;
  }

   /**
   * List of vendor related accounts. For a material_supplier vendor, at least one active account must be defined.
   * @return account
  **/

  @ApiModelProperty(value = "List of vendor related accounts. For a material_supplier vendor, at least one active account must be defined.")
  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=
  @JacksonXmlElementWrapper(useWrapping = true, localName = "account")

  public List<Account> getAccount() {
    return account;
  }


  public void setAccount(List<Account> account) {
    this.account = account;
  }


  public Vendor contactPerson(List<ContactPerson> contactPerson) {
    
    this.contactPerson = contactPerson;
    return this;
  }

  public Vendor addContactPersonItem(ContactPerson contactPersonItem) {
    if (this.contactPerson == null) {
      this.contactPerson = new ArrayList<ContactPerson>();
    }
    this.contactPerson.add(contactPersonItem);
    return this;
  }

   /**
   * Get contactPerson
   * @return contactPerson
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTACT_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=
  @JacksonXmlElementWrapper(useWrapping = true, localName = "contactPerson")

  public List<ContactPerson> getContactPerson() {
    return contactPerson;
  }


  public void setContactPerson(List<ContactPerson> contactPerson) {
    this.contactPerson = contactPerson;
  }


  public Vendor _interface(List<AlmaInterface> _interface) {
    
    this._interface = _interface;
    return this;
  }

  public Vendor addInterfaceItem(AlmaInterface _interfaceItem) {
    if (this._interface == null) {
      this._interface = new ArrayList<AlmaInterface>();
    }
    this._interface.add(_interfaceItem);
    return this;
  }

   /**
   * List of the vendor&#39;s related interfaces. Relevant only for an Access Provider vendor.
   * @return _interface
  **/

  @ApiModelProperty(value = "List of the vendor's related interfaces. Relevant only for an Access Provider vendor.")
  @JsonProperty(JSON_PROPERTY_INTERFACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  // items.xmlName=
  @JacksonXmlElementWrapper(useWrapping = true, localName = "_interface")

  public List<AlmaInterface> getInterface() {
    return _interface;
  }


  public void setInterface(List<AlmaInterface> _interface) {
    this._interface = _interface;
  }


  public Vendor contactInfo(ContactInfo contactInfo) {
    
    this.contactInfo = contactInfo;
    return this;
  }

   /**
   * Get contactInfo
   * @return contactInfo
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTACT_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "contact_info")

  public ContactInfo getContactInfo() {
    return contactInfo;
  }


  public void setContactInfo(ContactInfo contactInfo) {
    this.contactInfo = contactInfo;
  }


  public Vendor ediInfo(EdiInfo ediInfo) {
    
    this.ediInfo = ediInfo;
    return this;
  }

   /**
   * Get ediInfo
   * @return ediInfo
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EDI_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "edi_info")

  public EdiInfo getEdiInfo() {
    return ediInfo;
  }


  public void setEdiInfo(EdiInfo ediInfo) {
    this.ediInfo = ediInfo;
  }


  public Vendor notes(Object notes) {
    
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/

  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "notes")
  public Object getNotes() {
    return notes;
  }


  public void setNotes(Object notes) {
    this.notes = notes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Vendor vendor = (Vendor) o;
    return Objects.equals(this.link, vendor.link) &&
        Objects.equals(this.code, vendor.code) &&
        Objects.equals(this.name, vendor.name) &&
        Objects.equals(this.additionalCode, vendor.additionalCode) &&
        Objects.equals(this.financialSysCode, vendor.financialSysCode) &&
        Objects.equals(this.nationalTaxId, vendor.nationalTaxId) &&
        Objects.equals(this.status, vendor.status) &&
        Objects.equals(this.liableForVat, vendor.liableForVat) &&
        Objects.equals(this.language, vendor.language) &&
        Objects.equals(this.materialSupplier, vendor.materialSupplier) &&
        Objects.equals(this.accessProvider, vendor.accessProvider) &&
        Objects.equals(this.licensor, vendor.licensor) &&
        Objects.equals(this.governmental, vendor.governmental) &&
        Objects.equals(this.taxPercentage, vendor.taxPercentage) &&
        Objects.equals(this.library, vendor.library) &&
        Objects.equals(this.currency, vendor.currency) &&
        Objects.equals(this.account, vendor.account) &&
        Objects.equals(this.contactPerson, vendor.contactPerson) &&
        Objects.equals(this._interface, vendor._interface) &&
        Objects.equals(this.contactInfo, vendor.contactInfo) &&
        Objects.equals(this.ediInfo, vendor.ediInfo) &&
        Objects.equals(this.notes, vendor.notes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(link, code, name, additionalCode, financialSysCode, nationalTaxId, status, liableForVat, language, materialSupplier, accessProvider, licensor, governmental, taxPercentage, library, currency, account, contactPerson, _interface, contactInfo, ediInfo, notes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Vendor2 {\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    additionalCode: ").append(toIndentedString(additionalCode)).append("\n");
    sb.append("    financialSysCode: ").append(toIndentedString(financialSysCode)).append("\n");
    sb.append("    nationalTaxId: ").append(toIndentedString(nationalTaxId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    liableForVat: ").append(toIndentedString(liableForVat)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    materialSupplier: ").append(toIndentedString(materialSupplier)).append("\n");
    sb.append("    accessProvider: ").append(toIndentedString(accessProvider)).append("\n");
    sb.append("    licensor: ").append(toIndentedString(licensor)).append("\n");
    sb.append("    governmental: ").append(toIndentedString(governmental)).append("\n");
    sb.append("    taxPercentage: ").append(toIndentedString(taxPercentage)).append("\n");
    sb.append("    library: ").append(toIndentedString(library)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    contactPerson: ").append(toIndentedString(contactPerson)).append("\n");
    sb.append("    _interface: ").append(toIndentedString(_interface)).append("\n");
    sb.append("    contactInfo: ").append(toIndentedString(contactInfo)).append("\n");
    sb.append("    ediInfo: ").append(toIndentedString(ediInfo)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

