/*
 * Ex Libris APIs
 * For more information on how to use these APIs, including how to create an API key required for authentication, see [Alma REST APIs](https://developers.exlibrisgroup.com/alma/apis).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.unidue.ub.alma.shared.user;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.xml.bind.annotation.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * A particular proxy for a user.
 */
@ApiModel(description = "A particular proxy for a user.")
@JsonPropertyOrder({
  ProxyForUser.JSON_PROPERTY_LINK,
  ProxyForUser.JSON_PROPERTY_PRIMARY_ID,
  ProxyForUser.JSON_PROPERTY_FULL_NAME
})

@XmlRootElement(name = "proxy_for_user")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "proxy_for_user")
public class ProxyForUser implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_LINK = "link";
  @XmlAttribute(name = "link")
  private String link;

  public static final String JSON_PROPERTY_PRIMARY_ID = "primary_id";
  @XmlElement(name = "primary_id")
  private String primaryId;

  public static final String JSON_PROPERTY_FULL_NAME = "full_name";
  @XmlElement(name = "full_name")
  private String fullName;


  public ProxyForUser link(String link) {
    
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(isAttribute = true, localName = "link")

  public String getLink() {
    return link;
  }


  public void setLink(String link) {
    this.link = link;
  }


  public ProxyForUser primaryId(String primaryId) {
    
    this.primaryId = primaryId;
    return this;
  }

   /**
   * The primary identifier.
   * @return primaryId
  **/
  @ApiModelProperty(example = "johns", value = "The primary identifier.")
  @JsonProperty(JSON_PROPERTY_PRIMARY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "primary_id")

  public String getPrimaryId() {
    return primaryId;
  }


  public void setPrimaryId(String primaryId) {
    this.primaryId = primaryId;
  }


  public ProxyForUser fullName(String fullName) {
    
    this.fullName = fullName;
    return this;
  }

   /**
   * The user&#39;s first and last name.
   * @return fullName
  **/
  @ApiModelProperty(example = "John W Smith", value = "The user's first and last name.")
  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "full_name")

  public String getFullName() {
    return fullName;
  }


  public void setFullName(String fullName) {
    this.fullName = fullName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProxyForUser proxyForUser = (ProxyForUser) o;
    return Objects.equals(this.link, proxyForUser.link) &&
        Objects.equals(this.primaryId, proxyForUser.primaryId) &&
        Objects.equals(this.fullName, proxyForUser.fullName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(link, primaryId, fullName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProxyForUser {\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    primaryId: ").append(toIndentedString(primaryId)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

